### ISSUE TITLE
checkout alters repo

### ISSUE THREAD

**Issue by eddelbuettel** [ropensci/git2r#109]
Likely bug report:   
- I am pretty certain that `checkout(repo, "gh-pages")` does not what `git checkout gh-pages` does.

I am in the process of adding git2r support to drat, and the checkout command (currently?) copies from my master into the gh-pages, which is not what the command does, and not what I'd like it to do.

I can probably supply more detail if you need it.  Is this something that has come up before?

git2r 0.7 as from CRAN; your commit history does not immediately suggest I should use the gh version.

**Comment by stewid** [comment]
I can reproduce the problem.

There are many different [options](https://github.com/libgit2/libgit2/blob/HEAD/include/git2/checkout.h#L24) in `libgit2` for checkout  and currently [GIT_CHECKOUT_SAFE_CREATE](https://github.com/ropensci/git2r/blob/master/src/git2r_checkout.c#L89) is the default  in `git2r`. If you run `checkout(repo, "gh-pages", force = TRUE)` you should get the same [result](https://github.com/libgit2/libgit2/blob/HEAD/include/git2/checkout.h#L72) as `git checkout --force gh-pages`

I have to investigate what option should be the default to get the same behaviour as `git checkout gh-pages`?

**Comment by eddelbuettel** [comment]
Oh man.  And I used to joke that git on the command-line is hard....   Poor you.

In a nutshell, I just want to switch from master to gh-pages, alter no files, run add over three files (the ones added by drat, plus updated PACKAGES and PACKAGES.gz), commit and push.  

I am currently having issues with checkout as stated here (so I fall back to `system("git checkout gh-pages")` which is poor programming style but works), can use git2r for add and commit (yay!) and fall on my face for push (where I probably just need a hint from you...).

Oh, and I added a littler command to tickle all this too :)

**Comment by stewid** [comment]
:smiley: 

https://github.com/ropensci/git2r/blob/master/tests/push.R
I have also pushed to GitHub with `git2r` https://github.com/stewid/playground

**Comment by eddelbuettel** [comment]
I basically [tried in drat::insertPackage()](https://github.com/eddelbuettel/drat/blob/master/R/insertPackage.R#L67-L73) what you have at the bottom of playground, but failed (with error `no auth socket` or some such).  

drat was due for an update / second upload.  So I've taken what we have now and pushed 0.0.2 to CRAN; hopefully I can count on you for the help I'll need to get it rocking with  git2r.

**Comment by stewid** [comment]
I have fixed checkout of a branch and added a test. Could you please check that it works.

**Comment by eddelbuettel** [comment]
I take your word for it -- drat 0.0.2 is still in incoming at CRAN; I'll revisit this once I start the next development cycle for 0.0.3 or whatever the next one will be called.

But I _really_ appreciate the prompt prompt.

**Comment by eddelbuettel** [comment]
Confirmed -- just upgraded to git2r as in git right now, and `checkout(repo, "gh-pages")` does exactly what you'd expect without any side-effects on copying files around.

Thanks!

**Comment by stewid** [comment]
Thanks for testing.
