### ISSUE TITLE
Method to create signatures?

### ISSUE THREAD

**Issue by noamross** [ropensci/git2r#112]
There doesn't appear to be a way to create commit signatures.  `commit()` takes both author and committer signatures, with `default_signature(repo)` as the default.  However, if I want to create a different signature, I need to call `default_signature(repo)` and then modify the slots manually, which usually isn't good practice for S4 objects.  It would be good for there to be a function like `signature(name, email, when)`.

My use-case is importing a google doc and it's history into a git repository.  I download all revisions using [driver](https://github.com/Ironholds/driver), then commit each, using their author and date in the author signatures.

**Comment by stewid** [comment]
Thanks for the suggestion to add a method `signature(name, email, when)`. However, there is already a class [`signature`](https://stat.ethz.ch/R-manual/R-devel/library/methods/html/signature-class.html) in `methods`.

You can use the `new` method to create a `git_signature`. I have added a help method to coerce a `POSIXlt` class to `git_time` to facilitate creation of a `git_signature`

```r
new("git_signature",
    name = "Alice",
    email = "alice@example.org",
    when = as(as.POSIXlt(Sys.time()), "git_time"))
```
```r
#> name:  Alice
#> email: alice@example.org
#> when:  2015-03-17 22:12:52
```

Could that work for your use case

**Comment by noamross** [comment]
Yes, that works great. Thanks!

**Comment by stewid** [comment]
Great.
