### ISSUE TITLE
Removing a file

### ISSUE THREAD

**Issue by dgrtwo** [ropensci/git2r#113]
I haven't found any function for removing/deleting a file from a git repository (or, if it is removed in the file system, from committing the fact that it's been removed). I've found only functions for removing a remote or deleting a branch. Is deleting a file possible with git2r?

**Comment by gaborcsardi** [comment]
Based on a quick glance, there is no such function in the wrapped C library, either. So, yes, just remove and commit, I guess. git2r could still provide such a function, much like command line git does.

**Comment by stewid** [comment]
Not supported yet. It seems we can wrap `libgit2` [git_index_remove_bypath](https://libgit2.github.com/libgit2/#HEAD/group/index/git_index_remove_bypath) to delete a file.

The names `remove` and `rm` are already in use in base R to remove objects. Is it ok to use the name `remove_file`?

**Comment by eddelbuettel** [comment]
You could even add it (so that us nerds get it) but not export it.  `git2r:::rm()` may be clearer from context that an exported and global `remove_file()` which does not reveal a git context.  My $0.02.

**Comment by dgrtwo** [comment]
@gaborcsardi I actually don't believe one can solve the problem by removing and committing. For instance, try running the following in a new directory:

    # setup
    git2r::init(".")
    repo <- git2r::repository(".")
    writeLines("File content", "test.txt")

    # add a file
    git2r::add(repo, "test.txt")
    git2r::commit(repo, message = "First commit")

    # remove file and commit
    unlink("test.txt")
    git2r::commit(repo, message = "Deleted file")

This gets the error:

    Error in git2r::commit(repo, message = "Deleted file") : 
      Error in 'git2r_commit': Nothing added to commit

The removal of the file is thus not staged. I've tried doing `git2r::add(repo, "test.txt")` after deleting the file (in the hopes it might "add" the fact that it was deleted), but that still doesn't stage it.

**Comment by eddelbuettel** [comment]
It's late and I have been traveling ... but methinks you may have the logic wrong.  The `unlink()` is a filesystem operation outside of git, I do not think that what you do here is that close that `git rm`.

Stefan has does fabulous work so far unearthing a few other commands based on what `/usr/bin/git` does.  There is after all some behaviour to be studied and copied, so I am moderately hopeful that we can get a `git rm` equivalent in the API.

**Comment by gaborcsardi** [comment]
@eddelbuettel Right, my mistake. I remembered that I had been doing this from the command line, but it only works with `commit -a`, and that just does the `git rm` in the background:

```bash
/tmp$ mkdir foo
/tmp$ cd foo
/tmp/foo$ git init .
Initialized empty Git repository in /private/tmp/foo/.git/
/tmp/foo (master)$ touch bar
/tmp/foo (master)$ git add bar
/tmp/foo (master)$ git commit -m "bar"
[master (root-commit) c3c3ef7] bar
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 bar
/tmp/foo (master)$ rm bar
/tmp/foo (master)$ git commit -a -m "remove bar"
[master 1636dd9] remove bar
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 bar
```

And of course there is an API call for this in libgit2....

**Comment by dgrtwo** [comment]
@eddelbuettel I think you misunderstood me: I was responding to Gabor's `just remove and commit` comment, and pointing out that it doesn't work as a replacement for `git rm` (which I think he has acknowledged :+1:)

**Comment by eddelbuettel** [comment]
@dgrtwo Indeed.  I should impose a new rule about not commenting in public for the first few hours after stepping off a plane.  My bad.

**Comment by stewid** [comment]
@dgrtwo I'm working on adding the `all` argument to `git2r::commit`.

**Comment by eddelbuettel** [comment]
I consider `git commit -a` to be a misfeature.  That's how people add .dll, .so, .o, ... files that don't belong.  Maybe I am picky here but is there no other way to cope with deletes?

**Comment by gaborcsardi** [comment]
@eddelbuettel I think `-a` is useful, but somewhat a sidetrack here.

I would definitely like to have `git rm` as well, it seems that all we need is wrapping `git_index_remove_bypath`.

**Comment by stewid** [comment]
I have added the `all` argument to `commit`. It adds unstaged modified and deleted files to the index. I have also added the C function `git2r_index_remove_bypath` to wrap `git_index_bypath`.

Now we need an R method to remove a file and call `git2r_index_remove_bypath`
Does it work to use `rm` since it takes `...` as its first argument???

**Comment by gaborcsardi** [comment]
@stewid `rm` is not generic, and also does non-standard evaluation, so this time maybe a different name would be better.

**Comment by stewid** [comment]
I have added `rm_file` to remove files from the working tree and from the index.

```
## Initialize a repository
path <- tempfile(pattern="git2r-")
dir.create(path)
repo <- init(path)
     
## Create a user
config(repo, user.name="Alice", user.email="alice@example.org")
     
## Create a file
writeLines("Hello world!", file.path(path, "file-to-remove.txt"))
     
## Add file to repository
add(repo, "file-to-remove.txt")
commit(repo, "First commit message")
     
## Remove file
rm_file(repo, "file-to-remove.txt")
     
## View status of repository
status(repo)
```
```
#> Staged changes:
#> 	Deleted:   file-to-remove.txt
```

**Comment by eddelbuettel** [comment]
That is great news. Thanks so much for adding this!
