### ISSUE TITLE
Checkout previous branch

### ISSUE THREAD

**Issue by stewid** [ropensci/git2r#114]
Hi @eddelbuettel

It's now possible to checkout previous branch with
```
checkout(repo, "-")
```

**Comment by eddelbuettel** [comment]
Great news, really appreciate it!

Something that came up during the unconf:  there is no way to do `git2r:rm()` (or related) to remove a file?

**Comment by stewid** [comment]
@dgrtwo opened an issue to remove a file https://github.com/ropensci/git2r/issues/113
