### ISSUE TITLE
Any way to pass equiv. of command line flags to `push()`?

### ISSUE THREAD

**Issue by sckott** [ropensci/git2r#115]
e.g., https://github.com/mbostock/gistup/blob/master/bin/gistup#L184 

trying to integrate `git2r` in gistr for pushing files to gists, and want to pass flags

**Comment by stewid** [comment]
> trying to integrate git2r in gistr for pushing files to gists, and want to pass flags

Great :+1: 

I have pushed to github with `git2r` https://github.com/stewid/playground
Please try `push(repo, argv.remote, "refs/heads/master")`

**Comment by sckott** [comment]
Is there any way to pass `-f` to `push()`? to force the push?

**Comment by stewid** [comment]
Not yet. But maybe it's easy to add to the push method. If I understand the git-push documentation correct, `force` means adding `+` before src in `refspec` http://git-scm.com/docs/git-push 

Could you please try if it works to call the underlying C code directly with the refspec `+src:dst` specified
```
library(git2r)
repo <- repository("some/path")
.Call(git2r:::git2r_push, repo, "origin", "+refs/heads/master:refs/heads/master", NULL)
```

If that works, we can add the force argument and prefix `refspec` https://github.com/ropensci/git2r/blob/master/R/push.r#L99

**Comment by sckott** [comment]
@stewid thanks. That works. Tried on normal git repo on github and for gists. Both seemed to work.

**Comment by stewid** [comment]
Thanks @sckott. I'll add the force argument.

**Comment by sckott** [comment]
:+1:

**Comment by stewid** [comment]
Done.

**Comment by sckott** [comment]
thanks
