### ISSUE TITLE
Bypass commit hooks

### ISSUE THREAD

**Issue by restonslacker** [ropensci/git2r#118]
It seems like there is no way currently to bypass commit hooks with git2r. Is this correct? I use a precommit hook to increment the version of package but there are times when I need/want to skip them.

**Comment by stewid** [comment]
Hooks are not supported by git2r and therefore pre-commit hooks are not processed.

If you have the following pre-commit file and commit from the command line, changes are not commited.

```
#!/bin/sh

exit 1
```

However, if you commit with git2r the commit is processed.
