### ISSUE TITLE
Determine if a directory is a git repository

### ISSUE THREAD

**Issue by hadley** [ropensci/git2r#122]
Could be as simple as checking for presence of `.git` directory, but would be nicer to use same code as `repository()`, but just returning a boolean.

**Comment by stewid** [comment]
Add a method `is_repository()`, use `getwd()` and `discover_repository` internally

**Comment by stewid** [comment]
@hadley should the method return true iff the current directory contains a repository, or should it also check parent directories? `discover_repository` walk across parent directories if nothing has been found.

```
setGeneric("is_respository",
           signature = "path",
           function(path)
           standardGeneric("is_repository"))

setMethod("is_repository",
          signature(path = "missing"),
          function (path)
          {
              ## Use getwd
          }
)

setMethod("is_repository",
          signature(path = "character"),
          function (path)
          {
              ## Use path
          }
)
```

**Comment by hadley** [comment]
I think it should check the parents - maybe call it `in_repository()` to be more clear?
