### ISSUE TITLE
Make clear what version of libgit2 is bundled

### ISSUE THREAD

**Issue by hadley** [ropensci/git2r#123]

**Comment by stewid** [comment]
I'm currently tracking libgit2 bleeding edge. Add a method `libgit2_sha` to return the sha of the bundled libgit2. Create a script to automatically generate the method when syncing libgit2 https://github.com/ropensci/git2r/blob/master/Makefile#L63

**Comment by hadley** [comment]
How does libgit2 version track to git version?

**Comment by gaborcsardi** [comment]
git does not use libgit2 afaik.

**Comment by hadley** [comment]
So when a new version of git comes out, what does that mean for libgit2? Effectively nothing, because it's mostly the command line interface that's changing, not the underlying data structures?

**Comment by gaborcsardi** [comment]
@hadley Yes, AFAIK. Only if the underlying data structures change, needs libgit2 an update to handle the new stuff.

**Comment by stewid** [comment]
It's now possible to use the two methods `libgit2_version()` and `libgit2_sha()` to get version and commit of the bundled libgit2

**Comment by hadley** [comment]
Nice, thanks! (BTW do you know you can close issues from commits?)

**Comment by stewid** [comment]
Thanks, I should start using it.
