### ISSUE TITLE
Eliminate verbose argument to status()

### ISSUE THREAD

**Issue by hadley** [ropensci/git2r#125]
By returning custom class with show method

**Comment by stewid** [comment]
I have removed the verbose argument and changed to return the list as S3 class git_status. Added method print.git_status. I have also added a status method with `signature(repo = "missing")` to enable e.g. `status()` instead of `status(repository("."))`

**Comment by stewid** [comment]
@hadley I have added the `...` argument to the status method which I think should fix the current problem with devtools::release version 1.8.0 together with git2r::status version 0.10.1

https://github.com/ropensci/git2r/blob/master/R/status.r#L74

My plan is to submit a new version to CRAN within a couple of days
