### ISSUE TITLE
Equivalent of ls-remote

### ISSUE THREAD

**Issue by hadley** [ropensci/git2r#130]
Is there a way to get the sha of a commit in a branch on a remote repo?

(I need this in devtools, because when installing a package from git, I always add the commit sha1 in the DESCRIPTION to make debugging user problems easier)

**Comment by hadley** [comment]
Actually, just realised I don't need this since I'm now cloning the repo locally

**Comment by hadley** [comment]
Hmmm, we need this again for devtools. How hard would it be to add?

**Comment by stewid** [comment]
@jimhester is working on this :+1:
