### ISSUE TITLE
Better ssh URLs support (in CRAN OSX and Windows binaries)

### ISSUE THREAD

**Issue by gaborcsardi** [ropensci/git2r#131]
Currently the OSX binary on CRAN does not seem to support remotes over SSH. I know that I can compile from source and then (if I have a local libssh2 install) they'll be supported.

I am just wondering if we can do this better for the CRAN binary as well, so that people do not need libssh2? E.g. we can check how command line git does it, it clearly does not link to libssh, and I guess it does not contain an ssh protocol implementation, although it might.....

**Comment by gaborcsardi** [comment]
Or, as @hadley noted, we can ask CRAN maintainers to link libssh2 statically on OSX when making the binaries.

**Comment by hadley** [comment]
@jeroenooms might have some hints about how to make this happen

**Comment by jeroenooms** [comment]
I used brew and rwinlib for my [git](https://github.com/jeroenooms/git) package (before I learned about git2r). Works on all platforms with full support for ssh/ssl.

**Comment by sckott** [comment]
Same problem on my osx box.  Works fine installing from source though.

**Comment by sckott** [comment]
@stewid any thoughts on this issue?

**Comment by stewid** [comment]
I can send an email to the CRAN maintainers and ask if it's possible to statically link libssh2 on OSX.

**Comment by sckott** [comment]
cool, thanks @stewid

**Comment by jeroenooms** [comment]
You should mail Simon for that, he maintains the builders for OSX. But last time I asked he didn't reply.

What I do for V8 and RMySQL is run a brew script on the server that builds and pulls in static libraries. It's very hacky but it works.

**Comment by stewid** [comment]
@jeroenooms thanks

**Comment by stewid** [comment]
I have not received any reply from Simon.

**Comment by stewid** [comment]
I have updated the configure script to download and build libssh2 (ver 1.6.0, https://github.com/libssh2/libssh2/releases/tag/libssh2-1.6.0) on OSX.

It seems to work as expected, but please test.

**Comment by stewid** [comment]
Maybe we can also do this better for the windows binary. @jeroenooms is it possible to add libssh2 to rwinlib?

**Comment by jeroenooms** [comment]
There is already a copy in the [libgit2](https://github.com/rwinlib/libgit2) repo.

**Comment by jeroenooms** [comment]
But maybe i should add a separate one for libssh2

**Comment by stewid** [comment]
That would be great, I think we need the libssh2 include files to build successfully.

**Comment by jeroenooms** [comment]
Okay I did a first attempt. Let me know if it works: https://github.com/rwinlib/libssh2/archive/v1.6.0.zip

**Comment by stewid** [comment]
Thanks

**Comment by stewid** [comment]
@jeroenooms, works like a charm. I have tested on win-builder (R-release and R-devel) and it passes. I have also successfully tested to clone and push with the built package from win-builder
https://github.com/stewid/playground/commit/d6429dcf10bda36b8e0bb5c411339ca12325008a

**Comment by stewid** [comment]
My plan is to submit a new version to CRAN within a couple of days

**Comment by sckott** [comment]
:+1:

**Comment by stewid** [comment]
@jeroenooms git2r also downloads ([configure.win](https://github.com/ropensci/git2r/blob/master/configure.win#L85)) and uses openssl from rwinlib. Would it be possible to update openssl to the latest release?

**Comment by jeroenooms** [comment]
Sure I'll do that asap. I don't think there are any relevant changes for `git` though?

**Comment by stewid** [comment]
Thanks. You're probably right.

**Comment by stewid** [comment]
On CRAN

**Comment by sckott** [comment]
great, i'll update gistr soon

**Comment by jeroenooms** [comment]
@stewid there is a new version of openssl on rwinlib: https://github.com/rwinlib/openssl/releases

**Comment by stewid** [comment]
@jeroenooms thanks
