### ISSUE TITLE
Set up upstream repo without push()

### ISSUE THREAD

**Issue by hadley** [ropensci/git2r#133]
(Would be solved by #131)

Is it possible to link a local branch with a remote branch without performing a push? I'm working on  `devtools::use_github()`, and I'd like to be able to at least set up the repo so that you can push from RStudio. Currently:

```R
git2r::remote_add(r, "origin", create$ssh_url)
git2r::branch_set_upstream(head(r), "origin/master")
# Error in git2r::branch_set_upstream(head(r), "origin/master") : 
#  Error in 'git2r_branch_set_upstream': Cannot set upstream for branch 'master'
```

What am I doing wrong?

**Comment by stewid** [comment]
I'll investigate if it's possible.

**Comment by stewid** [comment]
I have not found a way to do that. However, the push method is improved with https://github.com/ropensci/git2r/issues/116 and https://github.com/ropensci/git2r/issues/131 fixed.
