### ISSUE TITLE
git2r build fail on OpenBSD (CRAN and github master)

### ISSUE THREAD

**Issue by pschmied** [ropensci/git2r#138]
Hello,

I was reinstalling devtools after upgrading R, and ran into a build failure with git2r. I'm on OpenBSD 5.7-current, amd64. The build appears to be failing when checking for OpenSSL. I suspect this has to do with OpenBSD having swapped out OpenSSL for LibreSSL (http://www.libressl.org/), and something in git2r's autoconf setup.

Other OpenSSL-using software seems to pick up LibreSSL as a replacement, so I'm guessing there is a cross-platform way of checking for both. That said, I are no autoconf genius. I'm posting this here in hopes that someone smarter than me will have an idea of what's going on there.

More than happy to test things, if anyone has suggestions!

Relevant ./configure bits:

    checking for library containing SSL_library_init... no
    configure: error: in `/home/peter/tmp/git2r':
    configure: error: OpenSSL library required
    See `config.log' for more details
    ERROR: configuration failed for package 'git2r'

And here are the bits from config.log:

    configure:3633: checking for library containing SSL_library_init
    configure:3664: cc -std=gnu99 -o conftest -O2 -pipe -I/usr/local/include/ereadline -I/usr/local/include -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I. -Ilibgit2 -Ilibgit2/include -Ihttp-parser  conftest.c -lz  >&5
    /tmp//ccMgCY3x.o(.text+0x7): In function `main':
    : undefined reference to `SSL_library_init'
    collect2: ld returned 1 exit status
    configure:3664: $? = 1
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "git2r"
    | #define PACKAGE_TARNAME "git2r"
    | #define PACKAGE_VERSION "see.DESCRIPTION.file"
    | #define PACKAGE_STRING "git2r see.DESCRIPTION.file"
    | #define PACKAGE_BUGREPORT "https://github.com/ropensci/git2r/issues"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | 
    | /* Override any GCC internal prototype to avoid an error.
    |    Use char because int might match the return type of a GCC
    |    builtin and then its argument prototype would still apply.  */
    | #ifdef __cplusplus
    | extern "C"
    | #endif
    | char SSL_library_init ();
    | int
    | main ()
    | {
    | return SSL_library_init ();
    |   ;
    |   return 0;
    | }
    configure:3664: cc -std=gnu99 -o conftest -O2 -pipe -I/usr/local/include/ereadline -I/usr/local/include -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I. -Ilibgit2 -Ilibgit2/include -Ihttp-parser  conftest.c -lssl  -lz  >&5
    /usr/lib/libssl.so.32.0: undefined reference to `EC_KEY_new_by_curve_name'
    /usr/lib/libssl.so.32.0: undefined reference to `EVP_rc4_hmac_md5'

    -- output truncated, lots of undefined refs --

    /usr/lib/libssl.so.32.0: undefined reference to `OBJ_bsearch_'
    /usr/lib/libssl.so.32.0: undefined reference to `EVP_DecryptFinal'
    collect2: ld returned 1 exit status
    configure:3664: $? = 1
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "git2r"
    | #define PACKAGE_TARNAME "git2r"
    | #define PACKAGE_VERSION "see.DESCRIPTION.file"
    | #define PACKAGE_STRING "git2r see.DESCRIPTION.file"
    | #define PACKAGE_BUGREPORT "https://github.com/ropensci/git2r/issues"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | 
    | /* Override any GCC internal prototype to avoid an error.
    |    Use char because int might match the return type of a GCC
    |    builtin and then its argument prototype would still apply.  */
    | #ifdef __cplusplus
    | extern "C"
    | #endif
    | char SSL_library_init ();
    | int
    | main ()
    | {
    | return SSL_library_init ();
    |   ;
    |   return 0;
    | }
    configure:3681: result: no
    configure:3763: error: in `/home/peter/tmp/git2r':
    configure:3765: error: OpenSSL library required
    See `config.log' for more details

**Comment by pschmied** [comment]
I should note this output is the result of a fresh checkout from github, and an `install.packages("~/tmp/git2r/", repos=NULL, type="source")`

**Comment by stewid** [comment]
@pschmied thanks for reporting the issue.

It seems the configuration is not picking up the correct path to the libressl header files. If you know the path it might work to pass it to the configure script. Could you please try (replace /path/to/libressl)

```
git clone https://github.com/ropensci/git2r.git
R CMD INSTALL --configure-args="--with-libssl-include=/path/to/libressl" git2r
```

**Comment by vats-div** [comment]
I received a similar error on an ubuntu machine when trying to install devtools.  

Installing libcryto++ and libssl-dev (using apt-get) fixed the problem.

**Comment by pschmied** [comment]
Thanks @stewid,

In this case, I'

**Comment by pschmied** [comment]
Okay, did some more digging, and was able to get the build to run. The library paths all appear to be correct, but the "LIBS" environment variable seems to not be set up properly. This results in a working build:

    R CMD INSTALL --configure-vars="LIBS='-lz -lcrypto -lssl'" git2r

That suggests to me that the include and library paths are all set up properly, but that the tests are failing. From the config.log, the bit of c code they compile as a test for `SSL_library_init ()` seems to be declaring a char return type, which doesn't seem to work for me with a toy example:

    % more foo.c 
    #include </usr/include/ssl/ssl.h>
    #include </usr/include/ssl/crypto.h>
    
    char SSL_library_init ();
    int main ()
    {
      return SSL_library_init ();
    }

    % gcc -lcrypto -lssl foo.c
    foo.c:5: error: conflicting types for 'SSL_library_init'
    /usr/include/ssl/ssl.h:1739: error: previous declaration of 'SSL_library_init' was here

Have no idea if that's relevant, but I thought that char return type looked suspicious from the config.log.

**Comment by stewid** [comment]
@pschmied thanks for the digging :+1: 

I have installed OpenBSD 5.7 on a virtual machine and can reproduce the issue.

**Comment by stewid** [comment]
@pschmied could you please try to install the `build_on_OpenBSD` branch. I have changed order of the libcrypto and libssl tests.

**Comment by pschmied** [comment]
Confirmed! build_on_OpenBSD branch builds without a hitch.

I appreciate you taking the time to create a fix for us non-Linux, Mac, Windows weirdos! ;-) On the upside, this should resolve future problems, if libressl becomes more common outside OpenBSD.

**Comment by stewid** [comment]
Thanks for testing
