### ISSUE TITLE
Push to Github

### ISSUE THREAD

**Issue by aruizga7** [ropensci/git2r#142]
Hi,

Is it possible to push repositories to Github? I am trying to find an example but I cannot find any...

Thanks!!!!!

**Comment by stewid** [comment]
Yes, I have successfully pushed to Github (https://github.com/stewid/playground) over ssh on my linux machine with my private key stored in a ssh-agent.

**Comment by stewid** [comment]
You have to build `git2r` with LibSSH2 installed

```r
library(git2r)
libgit2_features()
```

```
#> $threads
#> [1] FALSE
#> 
#> $https
#> [1] TRUE
#> 
#> $ssh
#> [1] TRUE
```

**Comment by aruizga7** [comment]
Right now I get:

> library(git2r)
> libgit2_features()
$threads
[1] FALSE

$https
[1] TRUE

$ssh
[1] FALSE

How can I build gir2r with LibSSH2 installed? I am using Windows. Thanks so much for the help!

**Comment by stewid** [comment]
Sorry, no support for SSH on Windows yet. I have not had any success to push over https, see https://github.com/ropensci/git2r/issues/116
