### ISSUE TITLE
add does not add files with a leading `./`

### ISSUE THREAD

**Issue by richfitz** [ropensci/git2r#145]
`git2r::add` treats `file` and `./file` separately, while git at the command line does not.  This turns out to cause trouble using `file.path` when `.` is passed in as the directory.

MWE, run in a new empty directory

```r
library(git2r)
init(".")
r <- repository(".")
writeLines("foo", "foo")
add(r, "./foo")
status(r) # foo not staged, but I think it should be
add(r, "foo")
status(r) # foo staged, as expected
commit(r, "foo added")
```

This is with git2r 0.10.1

**Comment by stewid** [comment]
Currently there is no pre-processing of the path prior to the call to the libgit2 function [git_index_add_all](https://libgit2.github.com/libgit2/#HEAD/group/index/git_index_add_all)

Another example that differs from command line git
```r
library(git2r)

r <- init(".")

writeLines("foo", "foo")
dir.create("foo_dir")
writeLines("foo-2", "foo_dir/foo")

setwd("./foo_dir")
add(r, "foo") # git2r stage foo.  Command line git stage foo_dir/foo if we cd to foo_dir
status(r)
```

```
## Untracked files:
## 	Untracked:  foo_dir/
##
## Staged changes:
## 	New:        foo
```

```r
add(r, "foo_dir/foo")
status(r)
```

```
## Staged changes:
## 	New:        foo
## 	New:        foo_dir/foo
```

It makes sense to have the same behaviour as command line git.

**Comment by jennybc** [comment]
This seems to be a more general phenomenon? Here's another reprex that puzzled me, involving `discover_repository()`:

``` r
library(git2r)

path <- file.path("~", "tmp", "testrepo")
dir.create(path)
r <- init(path)

discover_repository(path)
#> NULL
discover_repository(normalizePath(path))
#> [1] "/Users/jenny/tmp/testrepo/.git/"

repository(path, discover = TRUE)
#> Error in validObject(.Object): invalid class "git_repository" object: invalid object for slot "path" in class "git_repository": got class "NULL", should be or extend class "character"
repository(normalizePath(path), discover = TRUE)
#> Local:    /Users/jenny/tmp/testrepo/
#> Head:     nothing commited (yet)
```

Pre-processing the path with `normalizePath()` seems to be a Very Good Idea?

**Comment by jennybc** [comment]
@stewid Are you for or against pre-processing the path with `normalizePath()`? I'm just wondering if removing from the milestone is "no" or "not now". I run into this fairly regularly, where I feel I've given a valid path but it contains `.` or `~` and a `git2r` function does not work as expected.

**Comment by stewid** [comment]
@jennybc it was "not now". I have added a branch `pre-process-path` to address the problems mentioned in this issue. The tests passes on Linux and OS X but unfortunately fails on Windows.

**Comment by stewid** [comment]
@jennybc Could you please test that it works as expected for the cases you are aware of?

**Comment by jennybc** [comment]
Yes I will. In fact I will test the various things that have been added in master that I care about, leading up to your release. What's your timeline for that?

**Comment by stewid** [comment]
My plan is to submit on December 4

**Comment by stewid** [comment]
I have fixed the pre-processing of the path in the `add` method, added more tests and updated the documentation with examples. The `pre-process-path` branch is now merged into `master`.
