### ISSUE TITLE
Add equivalent of --force to add?

### ISSUE THREAD

**Issue by richfitz** [ropensci/git2r#148]
As documented in the reference, `git2r::add` does not add files that are ignored.  However, this is causing me problems where files are blanket ignored by a global gitignore (e.g., .gz files) and I can't override this.

I also tried a overriding the ignore with a .gitignore file that contained:

```
!*.gz
```

which overrides the ignore with system git, but git2r still did not add the files.

**Comment by stewid** [comment]
@richfitz Thanks

- [ ] Add force argument to [add](https://github.com/ropensci/git2r/blob/73c0f5612f4edec6bd5d8be590e44325cb539a97/R/index.r#L49) method with default value `FALSE`
- [ ] Add force argument to [git2r_index_add_all](https://github.com/ropensci/git2r/blob/73c0f5612f4edec6bd5d8be590e44325cb539a97/src/git2r_index.c#L76) 
- [ ] Use [GIT_INDEX_ADD_FORCE](https://libgit2.github.com/libgit2/#HEAD/group/index/git_index_add_all) in [git2r_index_add_all](https://github.com/ropensci/git2r/blob/73c0f5612f4edec6bd5d8be590e44325cb539a97/src/git2r_index.c#L76)
- [ ] Add test case
