### ISSUE TITLE
Can't load git2r

### ISSUE THREAD

**Issue by yocra3** [ropensci/git2r#150]
Hi!

I recently updated R to the new version and now devtools imports your package. During installation, there are no problems. However, when I try to load your packages the following message appears: 

Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Documents and Settings/cruiz.CREAL/Mis documentos/R/win-library/3.2/git2r/libs/i386/git2r.dll':
  LoadLibrary failure:  No se encontró el proceso especificado.

Error: package or namespace load failed for ‘git2r’

Thank you

My session info: 

R version 3.2.0 (2015-04-16)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows XP (build 2600) Service Pack 3

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.0

**Comment by stewid** [comment]
Hi @yocra3  

git2r version 0.10.1 does not work on Windows XP, see #139 
However, @justa9 successfully installed the older version git2r (0.7) on Windows XP, see #139 for instructions.

Thanks for reporting
