### ISSUE TITLE
Warnings if rm_file is called with more than one argument

### ISSUE THREAD

**Issue by krlmlr** [ropensci/git2r#151]
It looks like each file is removed as many times as the length of the `path` argument. Reproducible example below. Tested with CRAN version and 61c5d08.

Initialization
--------------

    repo_path <- tempfile()
    dir.create(repo_path)
    repo <- git2r::init(repo_path)
    invisible(lapply(file.path(repo_path, letters), writeLines, text = ""))
    git2r::add(repo, letters)
    git2r::commit(repo, "init")

    ## [ecbb2be] 2015-06-16: init

Strange warnings
----------------

    git2r::rm_file(repo, letters[1])
    git2r::commit(repo, "remove")

    ## [b66e9c2] 2015-06-16: remove

    git2r::rm_file(repo, letters[2:3])

    ## Warning in file.remove(paste0(workdir(repo), path)): cannot remove file '/
    ## tmp/RtmpMMspsb/file5e7f772c27dc/b', reason 'No such file or directory'

    ## Warning in file.remove(paste0(workdir(repo), path)): cannot remove file '/
    ## tmp/RtmpMMspsb/file5e7f772c27dc/c', reason 'No such file or directory'

    git2r::commit(repo, "remove")

    ## [4b2f1d8] 2015-06-16: remove

    git2r::rm_file(repo, letters[4:6])

    ## Warning in file.remove(paste0(workdir(repo), path)): cannot remove file '/
    ## tmp/RtmpMMspsb/file5e7f772c27dc/d', reason 'No such file or directory'

    ## Warning in file.remove(paste0(workdir(repo), path)): cannot remove file '/
    ## tmp/RtmpMMspsb/file5e7f772c27dc/e', reason 'No such file or directory'

    ## Warning in file.remove(paste0(workdir(repo), path)): cannot remove file '/
    ## tmp/RtmpMMspsb/file5e7f772c27dc/f', reason 'No such file or directory'

    ## Warning in file.remove(paste0(workdir(repo), path)): cannot remove file '/
    ## tmp/RtmpMMspsb/file5e7f772c27dc/d', reason 'No such file or directory'

    ## Warning in file.remove(paste0(workdir(repo), path)): cannot remove file '/
    ## tmp/RtmpMMspsb/file5e7f772c27dc/e', reason 'No such file or directory'

    ## Warning in file.remove(paste0(workdir(repo), path)): cannot remove file '/
    ## tmp/RtmpMMspsb/file5e7f772c27dc/f', reason 'No such file or directory'

    git2r::commit(repo, "remove")

    ## [8ce80e1] 2015-06-16: remove

Not shown
---------

    #git2r::rm_file(repo, letters[7:10])
    #git2r::commit(repo, "remove")
    #git2r::rm_file(repo, letters[11:26])
    #git2r::commit(repo, "remove")

**Comment by stewid** [comment]
Thanks @krlmlr
