### ISSUE TITLE
There is a problem when library of git2r

### ISSUE THREAD

**Issue by Gofer51** [ropensci/git2r#158]
OS: Windows XP 3
R: 3.2.1
RStudio: 0.99.467
devtools: 1.8.0
git2r: 0.10.1

After the error message I have reistalled git2r package but the problem is always present. 

![image](https://cloud.githubusercontent.com/assets/13706748/9150878/3bf8cd72-3dee-11e5-9926-3ca3fb0f53eb.png)

library("git2r", lib.loc="C:/Programmi/R/R-3.2.1/library")
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
unable to load shared object 'C:/Programmi/R/R-3.2.1/library/git2r/libs/i386/git2r.dll':
LoadLibrary failure: Impossibile trovare la procedura specificata.(*)
Error: package or namespace load failed for ‘git2r’

(*)Translate: It's not possible find specified procedure.

**Comment by stewid** [comment]
Hi @Gofer51 

git2r version 0.10.1 does not work on Windows XP, see #139 

Thanks for reporting
