### ISSUE TITLE
pull cannot use authentication credentials

### ISSUE THREAD

**Issue by jefferis** [ropensci/git2r#160]
I'm not sure if I'm missing something, but as far as I can see although you can give special authentication `credentials` to `fetch`, I see no way to do this for `pull`. So `pull`ing  a remote repository gives errors like this:

```r
> r=repository(path=".")
> cred=cred_ssh_key("~/.ssh/id_rsa.pub", "~/.ssh/id_rsa")
> fetch(r, "origin", credentials=cred)
> pull(r)
Error in fetch(repo, branch_remote_name(upstream_branch)) : 
  Error in 'git2r_remote_fetch': error authenticating: no auth sock variable
```

Am I missing something? Thanks!

**Comment by stewid** [comment]
Thanks  for reporting this. I have added the credentials argument to pull.
