### ISSUE TITLE
openssl deprecation will break git2r on OS X 10.11

### ISSUE THREAD

**Issue by tdsmith** [ropensci/git2r#162]
I noticed that git2r builds against openssl and tested that it doesn't build without system openssl headers. Apple has deprecated openssl and is not shipping openssl headers with OS X 10.11, so builds of git2r will fail unless users have set CPPFLAGS and LDFLAGS to allow a user-installed openssl to be discovered.

I will add appropriate flags to the Makeconf of the R build that Homebrew distributes. If you wish to try to autodetect Homebrew's openssl for users of the r-project.org build, the best way to do that would be to add "-I$(brew --prefix openssl)/include" and "-L$(brew --prefix openssl)/lib" to CPPFLAGS and LDFLAGS if `brew` exists in PATH.

**Comment by stewid** [comment]
I will add your suggestion to the configuration.

I noticed that version `0.23.0` of `libgit2` changed to use SecureTransport on Mac OS X to provide the cryptographic support for HTTPS connections instead of OpenSSL but have not had time to look at it https://github.com/libgit2/libgit2/releases

**Comment by stu-blair** [comment]
Hi, I think I am suffering from this issue, as I cannot install git2r after upgrading to OSX 10.11 --

    Error in dyn.load(file, DLLpath = DLLpath, ...) :
      unable to load shared object '/usr/local/lib/R/3.2/site-library/git2r/libs/git2r.so':
      dlopen(/usr/local/lib/R/3.2/site-library/git2r/libs/git2r.so, 6): Symbol not found: _gcry_cipher_close
      Referenced from: /usr/local/lib/R/3.2/site-library/git2r/libs/git2r.so
      Expected in: flat namespace
     in /usr/local/lib/R/3.2/site-library/git2r/libs/git2r.so
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing ‘/usr/local/lib/R/3.2/site-library/git2r’

@tdsmith / @stewid -- Can you please suggest a solution so I can git2r working again while this issue is still open? I see that I need to "set CPPFLAGS and LDFLAGS to allow a user-installed openssl to be discovered", and I'm guessing also install openssl, but I'm not sure how to best go about that. Thank you!

**Comment by tdsmith** [comment]
I noticed that `/usr/local/lib/R/3.2/site-library` exists, which is a convention that Homebrew employs; are you using the Homebrew distribution of R? If you are, you are probably not seeing this exact problem, especially if you've run `brew update && brew upgrade` recently, since Homebrew configures around it.

The full output of `install.packages()` (posted as a [gist](https://gist.github.com)) and the output (if applicable) of `brew config` and `brew doctor` could be helpful.

**Comment by stu-blair** [comment]
@tdsmith , thank you so much for helping! Yes, I am using the Homebrew distribution of R.

Output of `brew config` : https://gist.github.com/stu-blair/399c9b108d99b875dd3c
Output of `brew doctor` : https://gist.github.com/stu-blair/792ddee67c9d52a20bff
Output of `install.packages('git2r')` : https://gist.github.com/stu-blair/8b1f331b5b3fa8abded0

**Comment by stewid** [comment]
@stu-blair thanks for the output. I hope to find time this weekend to work on this.

**Comment by stu-blair** [comment]
@stewid thanks for the prompt response. I really appreciate it.

**Comment by stewid** [comment]
I have started to work on the [configuration](https://github.com/ropensci/git2r/blob/os_x_framework/configure.ac#L128) to use SecureTransport on OS X in the `os_x_framework` branch. For now, I have disabled the use of openssl on OS X. However, I don't have access to OS X to test if the configuration/build works.

@tdsmith could you please help me and test if the configuration is even close to work?

**Comment by iros** [comment]
Just checked against the os_x_framework branch and I cannot run `make install`. 

Seeing this:

```
make install
cd .. && R CMD INSTALL git2r
* installing to library ‘/usr/local/Cellar/r/3.1.2_1/R.framework/Versions/3.1/Resources/library’
* installing *source* package ‘git2r’ ...
checking build system type... x86_64-apple-darwin14.5.0
checking host system type... x86_64-apple-darwin14.5.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for library containing inflate... -lz
configure: error: in `/Users/iros/tmp/git2r':
configure: error:
  ---------------------------------------------
   Configuration of SSL failed
  ---------------------------------------------
See `config.log' for more details
ERROR: configuration failed for package ‘git2r’
* removing ‘/usr/local/Cellar/r/3.1.2_1/R.framework/Versions/3.1/Resources/library/git2r’
make: *** [install] Error 1
```

**Comment by iros** [comment]
Note that I was able to install from `master` with the following:

`OPENSSL_INCLUDES="/usr/local/opt/openssl/include/" make install`

**Comment by stewid** [comment]
@iros thanks for testing, much appreciated. I have changed the configuration, could you please try the `os_x_framework` branch again.

**Comment by iros** [comment]
This is what I'm seeing so far:

```
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/3.2/site-library/git2r/libs/git2r.so':
  dlopen(/usr/local/lib/R/3.2/site-library/git2r/libs/git2r.so, 6): Symbol not found: _EVP_aes_128_cbc
  Referenced from: /usr/local/lib/R/3.2/site-library/git2r/libs/git2r.so
  Expected in: flat namespace
 in /usr/local/lib/R/3.2/site-library/git2r/libs/git2r.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/3.2/site-library/git2r’
* restoring previous ‘/usr/local/lib/R/3.2/site-library/git2r’
make: *** [install] Error 1
```

**Comment by stewid** [comment]
@iros thanks

**Comment by stu-blair** [comment]
Thanks for the workaround, @iros , it enabled me to proceed with my work!

**Comment by datafig** [comment]
@stu-blair when you say it worked, did you mean by using the git2r that get's downloaded by `install.package('git2r')` or by manually downloading the master `git clone. I am encountering the same issue that you described since I upgraded to El Capitan.

**Comment by crsh** [comment]
`brew install openssl` fixed this problem for me.

**Comment by datafig** [comment]
@crsh i might be doing something wrong then. I have `openssl` installed using `brew` have made the suggested changes in `~/.R/Makeconf` and I am still getting the same build errors. I have a gist uploaded with the output here.

[Gist with output](https://gist.github.com/datafig/a84b23f83940ddf2caa3)

**Comment by adlersantos** [comment]
I had the same problem above and I have a brew installed R on El Capitan. I traced it down to not having libgit2 installed on Homebrew. So `brew install libgit2` did it for me. :)

**Comment by stewid** [comment]
@adlersantos great that it worked to install `git2r`. I don't have OS X and therefore no experience with brew. However, `git2r` does not link to the libgit2 library. The libgit2 source code is bundled with `git2r` and built when installing `git2r`. I have been working on the OS X configuration and also added 'osx' to
the Travis CI where `git2r` now builds ok. When you install libgit2, is any other library installed that could explain why it works? What was the specific problem you had when installed, before installing libgit2?

**Comment by jennybc** [comment]
@stewid I am a recent success story as counterpoint. I set up a fresh OS X El Capitan machine in the past week and just successfully installed `git2r` from GitHub and have used it. I do get quite a lot of compiler warnings. I use homebrew but have not explicitly done any the above re `openssl` or `libgit2`. Let me know if there is other information I can provide that might shed light on why it "just works" for me.

**Comment by crsh** [comment]
@datafig I'm not sure if this explains the different results you are getting, but I was working of a fresh install of El Capitan and installed `R` and `openssl` via homebrew. I did not make any changes to the `~/.R/Makeconf`.

**Comment by jennybc** [comment]
From re-reading the above, I suspect everyone else on this thread has installed R itself using homebrew? Whereas I have not -- I downloaded the Mac OS binary from [CRAN](https://cran.r-project.org/bin/macosx/). And then installed dev version of `git2r` via `devtools::install_github()`.

**Comment by datafig** [comment]
@jennybc i believe that is the case. I have installed `R` using homebrew. I have now installed `openssl` and `libgit2` also using `brew`. But still unable to successfully execute `install.package('git2r')`. And since `devtools` depends upon `git2r` i cannot install `devtools`. 

I have tried this on 3 separate machines with fresh El Capitan. I believe I can just download the R binary from CRAN and get it over with :)

**Comment by crsh** [comment]
@jennybc Yes, except that I, like @datafig, installed `git2r` (as a dependency for devtools) from CRAN.

**Comment by jennybc** [comment]
Wrt to `git2r`, I had success with both. Week one: I was using `git2r` installed from CRAN. As of yesterday: I'm using `git2r` installed from github via `devtools` (from GitHub if *that* could possibly matter?). I have done some other system set up with `homebrew` so it's possible some happy coincidence has worked in my favor. But nothing stands out as being clearly relevant to this thread.

**Comment by stewid** [comment]
@datafig Could you please try again. I have added the option `--with-openssl` to the build configuration of LibSSH2. That library can be built with OpenSSL or libcrypt for crypto. It should be `OpenSSL` but for some reason the configuration uses `Crypto library: libgcrypt` when you install `git2r`, see your [gist](https://gist.github.com/datafig/a84b23f83940ddf2caa3#file-git2r_error-L306).

**Comment by datafig** [comment]
@stewid Thanks, I was able to install from the development branch by cloning the master and performing the install.

**Comment by stewid** [comment]
@datafig Thanks for testing and great to hear that it worked :smiley:

**Comment by stewid** [comment]
I close this issue now, but please open if needed
