### ISSUE TITLE
Expose git_remote_set_url

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#167]
AFAICT the libgit2 code for `git_remote_set_url` is included here, but is not exposed via `git2r`.

**Comment by jennybc** [comment]
And so, to change the URL associated with an existing remote, you have to remove the remote then add it back with old name but new URL.

**Comment by stewid** [comment]
Thanks @jennybc

I have added the `remote_set_url` method which internally calls libgit2 `git_remote_set_url`
