### ISSUE TITLE
Is there a way to query user's global config?

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#168]
Does `git2r` provide a way to do the equivalent of this?

```
Jennifers-2015-MacBook-Pro:~ jenny$ git config --global --get user.name
jennybc
```

It feels like currently all access to git config info is tied to a specific repo?

**Comment by stewid** [comment]
No, `git2r` does not yet support that. It's on my wishlist though.

**Comment by jennybc** [comment]
Just a special plea for this. But I realize you need to work through your wishlist in the way that makes most sense globally.

I am thinking of wrapping some of `git2r` in a small user-oriented package, at least for my STAT545 students, and this would be super useful.

Right now RStudio is a very incomplete Git client and it would be nice to compensate by filling the worst gaps with `git2r`. I'd like to be able to verify certain aspects of git configuration from within R. Also adding remotes and setting upstream/tracking branch. This are very painful missing pieces. If I could wrap just that, most students wouldn't need to go to the shell for a long time. The whole shell thing is miserable with novices, esp. on Windows :frowning: 

While I'm wishing ... can we also **set** global config?

**Comment by stewid** [comment]
I look into this tomorrow.

Could something like this work?
```
config_get(repo, global, key)
config_set(repo, global, key, value)
```

**Comment by jennybc** [comment]
Well, my hope is to query and set user's global config, i.e. to provide `git2r` equivalents of:

``` shell
git config --global user.name 'Jenny Bryan'
git config --global user.email 'jenny@stat.ubc.ca'
git config --global --list
```

and *not* tie the ability to do this to a specific repo.

**Comment by restonslacker** [comment]
@JennyBryan wrt windows, have you tried using Atlassian sourcetree? Agree not having to introduce another tool is ideal,  but sourcetree is pretty easy to use for novices (once you get them through key pair generation).

**Comment by jennybc** [comment]
Yes, we are big recommenders of SourceTree! I am a heavy user myself.

But in terms of writing lessons and getting from point A to B in 1.5 hours of class, I'd love to have a pure R/RStudio solution. We know that's installed and current on all the machines. I'd prefer to not have SourceTree as a dependency, so to speak.

Also I have some Linux folks in the room (though they are generally comfortable in the shell).

**Comment by stewid** [comment]
I have updated the `config` method to work without a repository argument. Please give it a try.

```
> library(git2r)
> config()
global:
        color.ui=false
        push.default=simple
        user.email=stefan.widgren@gmail.com
        user.name=Stefan Widgren
```

The local configuration is included if the working directory is inside a repository.

```
> getwd()
[1] "/home/stefan/projects/packages/git2r"
> setwd("/home/stefan/projects/packages/git2r/git2r")
> config()
global:
        color.ui=false
        push.default=simple
        user.email=stefan.widgren@gmail.com
        user.name=Stefan Widgren
local:
        branch.master.merge=refs/heads/master
        branch.master.remote=origin
        branch.respect_http_sslverify_false.merge=refs/heads/respect_http_sslverify_false
        branch.respect_http_sslverify_false.remote=origin
        core.bare=false
        core.filemode=true
        core.logallrefupdates=true
        core.repositoryformatversion=0
        git2r.sessioninfo=true
        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
        remote.origin.push=:
        remote.origin.url=git@github.com:ropensci/git2r.git
```

The `config` method returns a list of class `git_config`

```
> str(config())
List of 2
 $ global:List of 4
  ..$ color.ui    : chr "false"
  ..$ push.default: chr "simple"
  ..$ user.email  : chr "stefan.widgren@gmail.com"
  ..$ user.name   : chr "Stefan Widgren"
 $ local :List of 12
  ..$ branch.master.merge                       : chr "refs/heads/master"
  ..$ branch.master.remote                      : chr "origin"
  ..$ branch.respect_http_sslverify_false.merge : chr "refs/heads/respect_http_sslverify_false"
  ..$ branch.respect_http_sslverify_false.remote: chr "origin"
  ..$ core.bare                                 : chr "false"
  ..$ core.filemode                             : chr "true"
  ..$ core.logallrefupdates                     : chr "true"
  ..$ core.repositoryformatversion              : chr "0"
  ..$ git2r.sessioninfo                         : chr "true"
  ..$ remote.origin.fetch                       : chr "+refs/heads/*:refs/remotes/origin/*"
  ..$ remote.origin.push                        : chr ":"
  ..$ remote.origin.url                         : chr "git@github.com:ropensci/git2r.git"
 - attr(*, "class")= chr "git_config"
```

I need to update the documentation.

**Comment by stewid** [comment]
Hi @jennybc 

I have done some more work on this issue and think we can close it.

> git config --global --get user.name

```r
config()$global$user.name
```

> git config --global user.name 'Jenny Bryan'

```r
config(global = TRUE, user.name = "Jenny Bryan")
```

> git config --global user.email 'jenny@stat.ubc.ca'

```r
config(global = TRUE, user.email = "jenny@stat.ubc.ca")
```

> git config --global --list

```r
config()
```

or 

```r
config()$global
```

**Comment by jennybc** [comment]
Thanks @stewid! I have been distracted by my course but will try this out today. This will be very handy.

**Comment by jennybc** [comment]
Very late to this party, but just wanted to confirm this is working and thank you for it!
