### ISSUE TITLE
Add cred_token class and method

### ISSUE THREAD

**Issue by stewid** [ropensci/git2r#170]
- Add S4 class `cred_token` with a character slot `token` to hold the name of the environmental variable with the secret.

- Add method `cred_token` to create a new `cred_token` object. Let `GITHUB_TOKEN` be the default value for the token name.

cc/ @jennybc

**Comment by jennybc** [comment]
:grinning: :grinning: 

Note: other packages from rOpenSci and in the Hadleyverse default to env var `GITHUB_PAT` for this. Any chance you'd make *that* the default?

**Comment by stewid** [comment]
Thanks, I'll change to `GITHUB_PAT`

Note: https://github.com/hadley/httr/blob/master/vignettes/api-packages.Rmd uses both `GITHUB_PAT` and `GITHUB_TOKEN`. Maybe it should be updated to use `GITHUB_PAT` only.

**Comment by stewid** [comment]
Changed default value to `GITHUB_PAT` in fe5313367878d1d778d50414df62893f4549de75

**Comment by jennybc** [comment]
Good point. I wrote that bit actually :flushed: before i fully caught on to the `GITHUB_PAT` convention.

**Comment by stewid** [comment]
:smiley:
