### ISSUE TITLE
Design question re: cred_env() and cred_token()

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#174]
Both `cred_env()` and `cred_token()` require the *names* of environment variables that hold username/password or GitHub PAT, respectively. I wonder if you might reconsider this in favor of functions that take the *values*. The user or calling package can easily do `Sys.getenv()` to pull these out of env vars.

With the current design, a package that uses `git2r` has to require that the user put this info into env vars AND elicit (or dictate) the associated names. Or has to wrap certain `git2r` functions inside `devtools::with_envvar()` [like so](https://github.com/jennybc/devtools/blob/5c18360226b895f1ae5366e34a96854bed01f278/R/infrastructure-git.R#L102-L104):

``` r
cred <- git2r::cred_env("EMAIL", "PASSWORD")
with_envvar(c("EMAIL" = "EMAIL", "PAT" = auth_token),
              git2r::push(r, "origin", "refs/heads/master", credentials = cred))
```

The current design seems restrictive for someone trying to use `git2r` inside other projects.

**Comment by stewid** [comment]
Thanks @jennybc. I take a closer look at the design today after work.

**Comment by stewid** [comment]
I suggest that you use `cred_user_pass` for this
```
cred <- git2r::cred_user_pass(Sys.getenv("EMAIL"), Sys.getenv("PASSWORD"))
git2r::push(r, "origin", "refs/heads/master", credentials = cred)
```
`cred_env` reads the values of the environmental variables `username` and `password` right before calling the libgit2 function `git_cred_userpass_plaintext_new`
https://github.com/ropensci/git2r/blob/master/src/git2r_cred.c#L115

`cred_user_pass` uses the variables `username` and `password` directly in the call to the libgit2 function `git_cred_userpass_plaintext_new`
https://github.com/ropensci/git2r/blob/master/src/git2r_cred.c#L196

**Comment by jennybc** [comment]
I had no idea `cred_user_pass()` existed. :disappointed: But I'm glad I do now!

It will be even easier than what you've got above. The email and password don't even necessarily live in environment variables -- I was only doing that in order to use `cred_env()`.
