### ISSUE TITLE
Invoking dlltool via make

### ISSUE THREAD

**Issue by jeroenooms** [ropensci/git2r#177]
The new rtools (gcc tool chain) requires some changes in `dlltool` flags which break the installation of git2r ([log](http://pastebin.com/raw.php?i=xwGtZBiz)). Currently you are manually calling `dlltool` in `configure.win`.  However the best way to ensure your package works both with the new and the old compilers is to use the dlltool macro from `Makeconf`. 

If you look in `C:/program files/R/R-3.2.2/etc/i386/Makeconf` (same for `x64`) you see something like this:

```make
M_ARCH = -m32
DT_ARCH = -m i386 --as-flags --32
RC_ARCH = -F pe-i386

DLLTOOL = $(BINPREF)dlltool --as $(BINPREF)as $(DT_ARCH)
DLLTOOLFLAGS = -k

lib%.dll.a: %.def
	$(DLLTOOL) $(DLLTOOLFLAGS) $($*-DLLTOOLFLAGS) --dllname $*.dll --input-def $*.def --output-lib $@
```

This means R will automatically convert `winhttp.def` into an import lib for `libwinhttp.dll.a` using the appropriate `dlltool` syntax. Therefore all you need to do is make sure the appropriate `winhttp.def` is in `src` and add a make dependency on `libwinhttp.dll.a` to your makevars. 

I added the same method (also for `winhttp.dll`) to the curl package. Feel free to steal the [makevars.win](https://github.com/jeroenooms/curl/blob/master/src/Makevars.win).

**Comment by stewid** [comment]
Thanks
