### ISSUE TITLE
Have you seen GitUp?

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#178]
Slightly off-topic, but here's a kind of wild, ambitious wrapper around libgit2 (Mac OS only):

<https://github.com/git-up/GitUp>

<http://gitup.co>

I will just close this myself shortly ... purely sharing w/ others interested in git wrappers. Obviously this occupies a totally different niche from `git2r`!

**Comment by gaborcsardi** [comment]
Gitup does *look* great, that's for sure. Haven't used it, though.

**Comment by stewid** [comment]
@jennybc thanks for sharing. Haven't used it (on Linux), but watched the video. It looks very impressive.
