### ISSUE TITLE
Cannot clone via http

### ISSUE THREAD

**Issue by jranke** [ropensci/git2r#180]
From the command line I can do

```
me@computer:~/tmp$ git clone http://cgit.jrwb.de/pfm
Cloning into 'pfm'...
Checking connectivity... done.
```

However, using git2r

```
> library(git2r)
> clone("http://cgit.jrwb.de/pfm", "pfm")
cloning into 'pfm'...
Error in clone("http://cgit.jrwb.de/pfm", "pfm") : 
  Error in 'git2r_clone': Invalid Content-Type: text/plain; charset=UTF-8
```

**Comment by stewid** [comment]
@jranke thanks for reporting the issue and providing a reproducible example.

I have to investigate what the problem is.

**Comment by stewid** [comment]
libgit2 does not support that content type, see https://github.com/libgit2/libgit2sharp/issues/1094

**Comment by jranke** [comment]
OK, so I think we can close the issue? Thanks anyways for the investigation. I did not know there was more than one way to have git talk over http.
