### ISSUE TITLE
Q: is it possible to checkout a specific file

### ISSUE THREAD

**Issue by jefferis** [ropensci/git2r#181]
I want to reset a specific file to its repository version. At the command line I can do this:

```sh
git checkout -- <file>
```
But I cannot see a way to do it with `git2r::checkout` or `git2r::reset`. Is this a missing feature? Or am I missing how to do it? Many thanks, Greg.

**Comment by stewid** [comment]
It is a missing feature, but I'm working on adding it

```
checkout(repo, path = "filename")
```

**Comment by jefferis** [comment]
Thanks!
