### ISSUE TITLE
ability to set GIT_OPT_SET_SSL_CERT_LOCATIONS for libgit2

### ISSUE THREAD

**Issue by rmflight** [ropensci/git2r#182]
It seems the latest version of `libgit2` allows one to set an SSL cert location. I think this should allow one to use remotes that have a self-signed certificate.

see bottom of https://libgit2.github.com/libgit2/#HEAD/group/libgit2/git_libgit2_opts

**Comment by stewid** [comment]
Thanks for the information. I have added the method `ssl_cert_locations` in branch `ssl_cert_locations`. Could you please test that it works.

**Comment by restonslacker** [comment]
I'll admit to this being a little out of my technical depth but the following didn't work for me:

```{r}
# download .crt files (4) from corporate website into ~/cert
devtools::install_github("ropensci/git2r", ref="ssl_cert_locations")
# restart R
library("git2r")
ssl_cert_locations(path="~/cert")
clone(url="https://<internal git server>/<project>.git", local_path="foo")
```

which produced the error:

`Error in 'git2r_clone': The SSL certificate is invalid.`

I know this isn't an MRE, but I wanted to check that this was the correct workflow to test against before I call in my IT department for help.

**Comment by rmflight** [comment]
Setting to a particular certificate worked for me.

```
devtools::install_github("ropensci/git2r", ref="ssl_cert_locations")
library(git2r)
creds <- new("cred_user_pass", username = "x", password = "y")
ssl_cert_locations(filename = "absolute path to certificate.crt")
clone(url="https://<internal server>/<project>.git", local_path = "local location")
```

No errors.

Also, pushing works as well with the `ssl_cert_locations` set.

I'm so happy I could cry!

**Comment by stewid** [comment]
Thanks for testing.

@rmflight that is really good news :smiley: 

@restonslacker could you please try with an absolute path `"/path/to/cert"`

**Comment by restonslacker** [comment]
Just to close the loop on my end, I was not able to get this branch to work properly even with full path names.  I spent time with our IT guys trying to diagnose it but don't have anything useful to report; it may just be due to our corporate proxy/firewall configurations.  

(In the end they wound up installing the corporate certs on the development machines and so the CRAN version of git2r now runs for me).  Thanks for developing this package!

**Comment by stewid** [comment]
@restonslacker thanks for the feedback
