### ISSUE TITLE
install from git - wrapper function

### ISSUE THREAD

**Issue by jangorecki** [ropensci/git2r#183]
While `devtools` do ths job very well I'm often forced to work in environment which lacks some of devtools dependencies - it grown over time and now has a chain of non-cran deps. On the other hand `git2r` requires only git which is usually available even on production environment. Currently I use bash commands to clone repo, switch to branch and install pkg. That works fine but it would be great to do it from R (easier scripting). The `git2r` could handle at least git part of that task.

**Comment by stewid** [comment]
The `git2r` package does not depend on git but bundles the C library [libgit2](https://libgit2.github.com/) within the [package](https://github.com/ropensci/git2r/tree/master/src/libgit2). You can clone and switch branch with `git2r` using `clone` and `checkout`

```{r}
## Create a temporary directory to hold the repository
path <- file.path(tempfile(pattern="git2r-"), "git2r")
dir.create(path, recursive=TRUE)

## Clone the git2r repository
repo <- clone("https://github.com/ropensci/git2r", path)

## Checkout a branch
checkout(repo, "ssl_cert_locations")
```
