### ISSUE TITLE
zlib dependency error should read zlib1g-dev

### ISSUE THREAD

**Issue by rnorberg** [ropensci/git2r#185]
I feel bad raising an issue as small as this one, but it might help a future user. 

**On Ubuntu 15.10**.  `install.packages("git2r")` fails with the error in the output shown below.

    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for library containing inflate... no
    configure: error: in `/tmp/RtmpvF8unA/R.INSTALL23c921c7292/git2r':
    configure: error: zlib library required
    See `config.log' for more details
    ERROR: configuration failed for package ‘git2r’

This is resolved by installation of `zlib1g-dev` via `sudo apt-get install zlib1g-dev`. It might save someone some googling if the error message said **zlib1g-dev** required instead of just "zlib". Or better yet, an error message like the following, which appears after installation of `zlib1g-dev`, but before successful installation of the package:

    checking for library containing EVP_EncryptInit... no
    configure: error: in `/tmp/RtmpzgSGM7/R.INSTALL2a7b142f42c/git2r':
    configure: error: 
      ---------------------------------------------
       OpenSSL library required
    
       Please install:
       libssl-dev (deb) or openssl-devel (rpm)
      ---------------------------------------------
    See `config.log' for more details
    ERROR: configuration failed for package ‘git2r’

This is a superb error message that even noobs like me can navigate. Something similar for the `zlib1g-dev` dependency would be sweet. 

Again, not trying to nit-pick, just hoping to help someone out in the future. Y'all are awesome.

**Comment by stewid** [comment]
Thanks for the suggestion :+1:
