### ISSUE TITLE
Link against external libgit2?

### ISSUE THREAD

**Issue by rekado** [ropensci/git2r#187]
I'm packaging `git2r` for GNU Guix and I wonder if it would be possible to link it against an existing installation of `libgit2` rather than building and linking the bundled copy.

**Comment by stewid** [comment]
The `git2r` package is not designed to link against an existing installation of `libgit2` but must use the bundled copy.

**Comment by rekado** [comment]
I understand.  Could this be achieved in the long run, though, by upstreaming the changes to the bundled libgit2 sources?

**Comment by stewid** [comment]
Maybe I misunderstand, but the development version of `git2r` usually contains the latest `libgit2` source code, see [commit messages](https://github.com/ropensci/git2r/commits/master) that starts with `Update libgit2 source code`
