### ISSUE TITLE
Can discover_repository be prevented from walking up the parents?

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#188]
I suspect this is out of your control.

But if you were so inclined, could `git2r::discover_repository(path)` have an additional argument that controls whether repo discovery is done *only for `path`* vs. walking up the parent directories?

**Comment by stewid** [comment]
Yes, that should be possible. The `libgit2` function [git_repository_discover](https://libgit2.github.com/libgit2/#HEAD/group/repository/git_repository_discover) takes one argument `ceiling_dirs` that is currently set to NULL https://github.com/ropensci/git2r/blob/master/src/git2r_repository.c#L541

I can add that.

**Comment by jennybc** [comment]
That would be extremely helpful! When it's not `NULL` what is it? Logical or a number or ???

**Comment by stewid** [comment]
I was thinking `NULL`  as default
`git2r::discover_repository(path, ceiling = NULL)`

And a character vector to use the feature, for example
`git2r::discover_repository(path, ceiling = getwd())`

**Comment by jennybc** [comment]
Yes agree that full walk has to be the default.

The character vector sounds pretty rough, though, for halting the walk early. I was thinking more like a positive integer specifying how many levels to go up: 0 = only attempt discovery in `path`, 1 = also consider the parent of `path`, etc. So full walk = Inf. You could then convert that to character, if that's what `git_repository_discover` requires, yes?

Even a binary toggle for walk up / don't walk would solve my particular problem.

**Comment by stewid** [comment]
I like your suggestion of using 0 and 1 for path and parent to path respectively.
