### ISSUE TITLE
Release v0.12.0

### ISSUE THREAD

**Issue by stewid** [ropensci/git2r#191]
Prepare release of version 0.12.0 on CRAN (v0.11.0 was released 2015-08-12)

* [x] Update NEWS
* [x] Update version string
* [x] Test on win-builder

**Comment by stewid** [comment]
Warning from test on win-builder #192

**Comment by jeroenooms** [comment]
👍👍We will try to push up the new windows tool chain soon. Would be great to get the new git2r release on cran before that, so that we have one less breaking package :)

**Comment by stewid** [comment]
:) My plan is to submit on Friday

Good luck with new windows tool chain :+1:

**Comment by stewid** [comment]
On CRAN
