### ISSUE TITLE
CPPFLAGS and GIT2R_CPPFLAGS

### ISSUE THREAD

**Issue by pooryorick** [ropensci/git2r#193]
In configure.ac, this line gives precedence to CPPFLAGS over GIT2R_CPPFLAGS

    CPPFLAGS="${CPPFLAGS} ${GIT2R_CPPFLAGS}"

CPPFLAGS, in turn, is derived from R:

    CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`

During the build, the .h files in src, libgit2, and regex must be found, but since $CPPFLAGS takes precedence, header conflicts can occur as GCC finds .h files by the same names in directories specified by $CPPFLAGS.  ONe solution would be to reverse the order in configure.ac:

    CPPFLAGS="$GIT2R_CPPFLAGS} ${CPPFLAGS}"

**Comment by stewid** [comment]
Thanks
