### ISSUE TITLE
package load fails on OS X El Capitan (OpenSSL related?)

### ISSUE THREAD

**Issue by kevinushey** [ropensci/git2r#195]
This is likely OpenSSL related (e.g. https://github.com/ropensci/git2r/issues/162), but posting this for posterity.

`R CMD INSTALL .` fails against current `master` of `git2r` as it cannot find the `_gcry_cipher_close` symbol:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/Users/kevinushey/Library/R/3.3/library/git2r/libs/git2r.so':
  dlopen(/Users/kevinushey/Library/R/3.3/library/git2r/libs/git2r.so, 6): Symbol not found: _gcry_cipher_close
  Referenced from: /Users/kevinushey/Library/R/3.3/library/git2r/libs/git2r.so
  Expected in: flat namespace
 in /Users/kevinushey/Library/R/3.3/library/git2r/libs/git2r.so
Error: loading failed
```

Note that this occurs even when I try to explicitly use a brew-installed version of OpenSSL (by amending `src/Makevars.in`):

```
kevinushey@Kevin-MBP:~/git/git2r/src [master]
$ otool -L git2r.so
git2r.so:
	git2r.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57336.10.29)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1255.1.0)
	/Library/Frameworks/R.framework/Versions/3.3/Resources/lib/libR.dylib (compatibility version 3.3.0, current version 3.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

**Comment by kevinushey** [comment]
I can resolve this by linking to `libgcrypt` explicitly (with `-lgcrypt`), although that's a separate library. Is that expected?

I imagine the package should be able to build against Apple's own crypto libraries?

**Comment by stewid** [comment]
All suggestions to improve the configuration are much appreciated. The libgit2 configuration is here https://github.com/libgit2/libgit2/blob/master/CMakeLists.txt

**Comment by stewid** [comment]
@kevinushey I have changed the configuration in the `configuration` branch to use `pkg-config` for `libssh2`. Could you please test if that works?

**Comment by kevinushey** [comment]
Well, this is bizarre -- I can no longer reproduce my original issue, neither on `master` or on `configuration`. :/

I thought it might be related to the presence / absence of a homebrew `libssh2` install, but the package seems to already properly detect whether it's available and use it if so...

Anyway, a `make clean && make install` seems to work fine both on `master` and `configuration` now. Sorry, and thanks for looking into this!

**Comment by stewid** [comment]
Thanks for testing both branches. Glad it worked :smiley:
