### ISSUE TITLE
openssl issue on CentOS

### ISSUE THREAD

**Issue by yueatwork** [ropensci/git2r#203]
I know this has been asked at many places. But no matter how hard I try, I cannot make it work. 

I always get the following issue:

configure: error:
-----------------------------------------------
  OpenSSL library required

  Please install:
  libssl-dev (deb) or openssl-devel (rpm)
-----------------------------------------------

so I tried to install openssl via both
1) yum install openssl-devel, and
2) install locally in my home directory.

But I still get the same error message. I looked at Config.log, and I see the error details:

configure:37-6: gcc -o confest -g -O2 -I/usr/local/include -L/usr/local/lib64 conftest.c -lcrypto -lz >&5

and it just cannot find symbols like 'dlopen', 'dlsym', 'dlclose', etc. (I see nothing in folder /usr/local/include and /usr/local/lib64, so I manually copied all files into these two folders)

I am sure my environment variables (C_INCLUDE_PATH, LIBRARY_PATH, LD_INCLUDE_PATH) are properly set. 

Is there something I missed?

**Comment by stewid** [comment]
Thanks for reporting the issue.

It is possible to specify the location of the header files and the library to the configuration script. To view the available options in git2r, please run
```
git clone https://github.com/ropensci/git2r.git
cd git2r
./configure --help
cd ..
```

To install the package with options for libssl, please use
```
R CMD INSTALL --configure-args='--with-libssl-include=/path/to/include --with-libssl-lib='/path/to/lib' git2r
```

Where you could try to use `pkg-config` to determine the paths.
```
pkg-config --cflags libssl
pkg-config --libs libssl
```

Hope this helps
