### ISSUE TITLE
Configure fails on OS X 10.7.5 when R uses non-system libiconv

### ISSUE THREAD

**Issue by mvkorpel** [ropensci/git2r#205]
I built a recent R development version (r69777) myself so that it uses [Homebrew](https://github.com/Homebrew/homebrew) versions of a few libraries (including zlib and iconv) instead of the fairly old system versions. The C compiler is also a Homebrew version, GCC 5.3.0. Let's call this "Build A".

With this R, neither the [CRAN version of git2r](https://CRAN.R-project.org/package=git2r) 0.13.1 nor the latest version on GitHub (commit [`7685619`](https://github.com/ropensci/git2r/commit/7685619c22438b132bc6898fc78aa030a5eceabb)) can be installed with a simple `install.packages()` or `devtools::install_github()`. The install fails with an error message in the `configure` script:

    configure: error: iconv library required
    See `config.log' for more details
    ERROR: configuration failed for package ‘git2r’

The latest CRAN version that can be installed (without any tweaking) is 0.11.0, and the latest such GitHub commit is [`ccd7ad1`](https://github.com/ropensci/git2r/commit/ccd7ad1f892b5a3a664702100449a301ea736c44). The `configure` error for failing builds is always the same as above.

If the build configuration of R is changed a bit so that the system version of iconv is used, this R build ("Build B") can install git2r 0.13.1 and the latest version on GitHub just fine.

Inspecting the various relevant dynamic libraries with `otool -L` reveals that `git2r.so` version 0.11.0 installed in Build A successfully links to Homebrew versions of zlib and iconv which are the same as those used by the corresponding `libR.dylib`. In Build B and `git2r.so` version 0.13.1, zlib is from Homebrew and iconv is the OS version, also matching the dependencies of the corresponding `libR.dylib`.

**Comment by mvkorpel** [comment]
I forgot to mention the reason why installing 0.12.1 failed. Although unrelated to the configure issue, this is relevant if you choose to reintroduce support for the SecureTransport framework at some point.

Using Build A as described above, the installation of git2r 0.12.1 failed with the following error messages (not actually on consecutive output lines):

    libgit2/stransport_stream.c:255:35: error: 'kSSLClientSide' undeclared (first use in this function)

    libgit2/stransport_stream.c:255:51: error: 'kSSLStreamType' undeclared (first use in this function)

    libgit2/stransport_stream.c:265:47: error: 'kTLSProtocol12' undeclared (first use in this function)

According to [Apple documentation](https://developer.apple.com/library/mac/documentation/Security/Reference/secureTransportRef/), these constants are available on OS X 10.8 and above.

When I configured a separate [libgit2](https://github.com/libgit2/libgit2) build with `cmake`, it reported the following:

    -- Looking for SSLCreateContext in /System/Library/Frameworks/Security.framework - not found
    -- Security framework is too old, falling back to OpenSSL

Maybe a similar check and fallback solution could be used by git2r.

**Comment by stewid** [comment]
Thanks for reporting the issue and the detailed description.

I'm working on improving the configuration and hopefully I will have something you can test in a few days.

The plan was to use `Security framework` on OS X, however, there was a significant compiler warning on CRAN (#197) with v0.12.1. Therefore, I went back to using OpenSSL.

**Comment by nipunbatra** [comment]
Hi there,
I am unable to install git2r on OSX 10.11. The error log is similar to the one in this thread.

```shell
cd .. && R CMD INSTALL git2r
* installing to library ‘/Users/nipunbatra/Library/R/3.2/library’
* installing *source* package ‘git2r’ ...
checking build system type... x86_64-apple-darwin15.0.0
checking host system type... x86_64-apple-darwin15.0.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for brew... yes
checking for library containing inflate... -lz
checking for library containing EVP_EncryptInit... -lcrypto
checking for library containing SSL_library_init... -lssl
checking for library containing libssh2_version... no
configure: Download and build libssh2
configure: error: unrecognized option: `-Wl,-headerpad_max_install_names'
Try `./configure --help' for more information
configure: WARNING:
  ---------------------------------------------
   Unable to find the LibSSH2 library on this
   system. Building a version without support
   for SSH transport.

   To build with SSH support, please install:
     libssh2-1-dev (package on e.g. Debian and Ubuntu)
     libssh2-devel (package on e.g. Fedora, CentOS and RHEL)
   and try again.

   If the LibSSH2 library is installed on
   your system but the git2r configuration
   is unable to find it, you can specify
   the include and lib path to LibSSH2 with:
   R CMD INSTALL --configure-args='--with-libssh2-include=INCLUDE_PATH --with-libssh2-lib=LIB_PATH' git2r
  ---------------------------------------------
checking for library containing iconv_open... no
configure: error: in `/Users/nipunbatra/git/git2r':
configure: error: 
  ---------------------------------------------
   The iconv library that is required to
   build git2r was not found.

   If the iconv library is installed on
   your system but the git2r configuration
   is unable to find it, you can specify
   the include and lib path to iconv with:
   R CMD INSTALL --configure-args='--with-iconv-include=INCLUDE_PATH --with-iconv-lib=LIB_PATH' git2r
  ---------------------------------------------
See `config.log' for more details
ERROR: configuration failed for package ‘git2r’
```

I wonder if there is a workaround?

**Comment by stewid** [comment]
@nipunbatra  Sorry, I don't know why you get `configure: error: unrecognized option: -Wl,headerpad_max_install_names`. You could try to install libssh2 with `brew install libssh2`.

**Comment by stewid** [comment]
@mvkorpel I have made several changes to the configuration, could you please if it works. It's also possible to use the following four configuration variables to specify optional paths for zlib and iconv: with-iconv-include, with-iconv-lib, with-zlib-include and with-zlib-lib, for example:
```
R CMD INSTALL --configure-args='--with-zlib-include=INCLUDE_PATH --with-zlib-lib=LIB_PATH' git2r
```

**Comment by mvkorpel** [comment]
@stewid Thanks, it works now. I did not need to set any configuration variables.

**Comment by stewid** [comment]
@mvkorpel Thanks for testing
