### ISSUE TITLE
Cannot set global user.name

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#206]
I was going to try and figure this out but am having trouble building `git2r` (see https://github.com/ropensci/git2r/issues/204#issuecomment-167062260 -- strangely I can install from github but then cannot build + install locally in any way, so cannot modify `git2r` to debug).

I can't seem to set global config.

``` r
library(git2r)
config(global = TRUE, user.name = "jenny")
#> Error in config(global = TRUE, user.name = "jenny"): Error in 'git2r_config_set': Invalid repository
session_info("git2r")
#> Session info --------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.2.3 (2015-12-10)
#>  system   x86_64, darwin13.4.0        
#>  ui       RStudio (0.99.825)          
#>  language (EN)                        
#>  collate  en_CA.UTF-8                 
#>  tz       America/Vancouver           
#>  date     2015-12-23
#> Packages ------------------------------------------------------------------
#>  package * version     date       source                         
#>  git2r   * 0.13.1.9000 2015-12-24 Github (ropensci/git2r@2754167)
```

**Comment by stewid** [comment]
Oops, I managed to break the code during the latest CRAN submission when I had to revert to an earlier version of the bundled libgit2 #198. Due to API changes in libgit2 I also had to revert `git2r_config.c` but by mistake I also removed the fix for the global config :-)

**Comment by jennybc** [comment]
YES 😀
