### ISSUE TITLE
git config variables

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#207]
I have two questions about the behaviour of `config()`.

[1] Why are `user.name` and `user.email` formal arguments? I seem to be able to query and set any [valid config variable](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration), so I'm just curious if there's something special about the handling of `user.name` and `user.email` that led to special treatment.

[2] If I attempt to set an unrecognized variable, it silently nullifies the entire operation and configuration is not changed (example below). I'm wondering if this behaviour comes from `git2r` or `libgit2`. If it's in `git2r` it might be nice to make the change that is valid and drop / warn about the impossible request. But I suspect this comes from `libgit2` and is something to work around.

``` r
library(git2r)
path <- tempfile(pattern = "git2r-")
dir.create(path)
repo <- init(path)

## let's set some valid local config vars
config(repo, user.name = "jenny", color.branch = "never")
lcfg <- config(repo)$local
lcfg[c("color.branch", "user.name")]
#> $color.branch
#> [1] "never"
#> 
#> $user.name
#> [1] "jenny"

## let's set one valid and one unrecognized config var
config(repo, user.email = "jenny@example.org", lol = "wut")
lcfg <- config(repo)$local
lcfg[c("color.branch", "user.name", "user.email", "lol")]
#> $color.branch
#> [1] "never"
#> 
#> $user.name
#> [1] "jenny"
#> 
#> $<NA>
#> NULL
#> 
#> $<NA>
#> NULL
## see ... even the valid request re: user.email is unsuccessful :(
```

**Comment by stewid** [comment]
**1**) The reason for having `user.name` and `user.email` as formal arguments is to facilitate the configuration with feedback and auto completion for the most frequently used variables e.g.

**Emacs**
![image](https://cloud.githubusercontent.com/assets/1815965/12033255/76ac1944-ae21-11e5-8577-e0677a781cd7.png)

**Rstudio**
![image](https://cloud.githubusercontent.com/assets/1815965/12033268/8edb65f6-ae21-11e5-901b-e66862ac5800.png)

**Terminal**
![image](https://cloud.githubusercontent.com/assets/1815965/12033290/b88c806a-ae21-11e5-8b7f-195428620dbf.png)

Do you have suggestions for some other variables to add?

**2**) I have identified the problem. The operation is terminated by any [error code](https://github.com/ropensci/git2r/blob/bbcc50fc8b695d82adc67a73d9b4a61fe0ec512d/src/git2r_config.c#L333) from libgit2. I have to change the code to check the error code and output a warning in case of an invalid name and then continue with the next variable.

**Comment by stewid** [comment]
I have fixed the code and added a test https://github.com/ropensci/git2r/commit/7b2990e9f0c42108984b54ec24947bdc9df7f3a1

```
library(git2r)
path <- tempfile(pattern = "git2r-")
dir.create(path)
repo <- init(path)

## let's set some valid local config vars
config(repo, user.name = "Stefan", color.branch = "never")
lcfg <- config(repo)$local
lcfg[c("color.branch", "user.name")]
#> $color.branch
#> [1] "never"
#> 
#> $user.name
#> [1] "Stefan"

## let's set one valid and one invalid config var
config(repo, user.email = "stefan@example.org", lol = "wut")
#> Warning message:
#> In config(repo, user.email = "stefan@example.org", lol = "wut") :
#>   Variable was not in a valid format: 'lol'
lcfg <- config(repo)$local
lcfg[c("color.branch", "user.name", "user.email", "lol")]
#> $color.branch
#> [1] "never"
#> 
#> $user.name
#> [1] "Stefan"
#> 
#> $user.email
#> [1] "stefan@example.org"
#> 
#> $<NA>
#> NULL
```
It is possible to use an unrecognized variables if the key is valid e.g. `example.lol=wut`
```
config(repo, example.lol = "wut")
lcfg <- config(repo)$local
lcfg[c("color.branch", "user.name", "user.email", "example.lol")]
#> $color.branch
#> [1] "never"
#> 
#> $user.name
#> [1] "Stefan"
#> 
#> $user.email
#> [1] "stefan@example.org"
#> 
#> $example.lol
#> [1] "wut"
```

**Comment by jennybc** [comment]
Re: `user.name` and `user.email`. Understood. This does make it harder to program around `git2r::config()`, which is what I'm trying to do. No, I don't have any recommendations for other variables to promote to formal arguments. If any should be treated that way, I think it's just these two.

Thanks for sorting out the behaviour re: unrecognized variables and for showing me how to set them!

**Comment by stewid** [comment]
> This does make it harder to program around `git2r::config()`

Let's improve the behaviour of the `git2r::config` method. What's your suggestion?
