### ISSUE TITLE
change requirement re: roxygen2 version

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#209]
I have `roxygen2` from github not CRAN. What do you think of changing the requirement from `== 5.0.1` to `>= 5.0.1`?

**Comment by stewid** [comment]
I think we can remove the version check entirely now when the roxygen version is written to RoxygenNote. The check was added to prevent changes (by misstake) to every Rd-file when the roxygen2 version (e.g 4.1.1) was written to each file. I can fix that.
