### ISSUE TITLE
Compiler flag -Wno-unused-function

### ISSUE THREAD

**Issue by stewid** [ropensci/git2r#212]
@jennybc I have added the compiler flag `-Wno-unused-function`. Do you get less compiler warnings now?

**Comment by jennybc** [comment]
It's hard to say ... but yes I think less. But still lots.

Here's what I could capture (again ... front part is lost 😞) from installing 068fbb2d6d74e7b730ad8164761100b4aa51ac98: [gist](https://gist.github.com/jennybc/3f1e0390aff07d387404)

And here is similar when installing from earlier commit 275416793ccca3f44e6d665bf7276b3c7d96b2f6: [gist](https://gist.github.com/jennybc/28097c56e77074cca6a8)

**Comment by stewid** [comment]
This is resolved now, when git2r uses a system installation of libgit2
