### ISSUE TITLE
Can't push using `cred_token()`

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#217]
I'm having trouble pushing when the credential is provided via `cred_token()`.

The previous workaround, using `cred_user_pass()` still works, so my PAT is good.

``` r
library(git2r)
## devtools::install_github("gaborcsardi/gh")
library(gh)

path <- tempfile(pattern="git2r-")
dir.create(path)
repo <- init(path)
writeLines("Hello world!", file.path(path, "example.txt"))
add(repo, "example.txt")
commit(repo, "First commit message")
#> [37abd6c] 2016-01-12: First commit message

## create a repo on github (or use the browser)
api_res <- gh("POST /user/repos",
              name = "git2r-reprex",
              description = "Description description description",
              private = "true")
origin_url <- api_res$clone_url ## this is the https url

remote_add(repo, "origin", origin_url)

cred <- cred_token(Sys.getenv("GITHUB_PAT"))
push(repo, "origin", "refs/heads/master", credentials = cred)
#> Error in .local(object, ...): Error in 'git2r_push': HTTP parser error: the on_headers_complete callback failed

cred <- cred_user_pass("EMAIL", Sys.getenv("GITHUB_PAT"))
push(repo, "origin", "refs/heads/master", credentials = red)
## successful!
```

**Comment by jennybc** [comment]
<img width="550" alt="git2r-reprex" src="https://cloud.githubusercontent.com/assets/599454/12288300/cc908432-b987-11e5-8d98-6a49fab30495.png">

**Comment by stewid** [comment]
The argument to `cred_token` is the name of the environment variable instead of the value. The default token name is `"GITHUB_PAT"`,  so please try
```
cred <- cred_token()
```

**Comment by jennybc** [comment]
Sure enough. User error. Sorry and thanks!

Observations about usability of the `cred_*()` functions ... `cred_user_pass()` wants the actual username and password, whereas `cred_token()` expects env var name. And `cred_ssh_key()` takes paths.

Re: `cred_token()`. I fed it a value because that is consistent wit `gh` and `devtools` . They both consult an env var by default (albeit with different default assumptions about name 😞) but user can override by providing an actual PAT, not a different env var name.

OTOH neither of those packages offers credential wrapping functions, like you do, so perhaps I shouldn't compare them.

**Comment by jennybc** [comment]
@stewid Are you willing to reconsider the input of `cred_token()`? Or create another `cred_*()` function that expects the token itself?

Both `devtools` and `gh` allow the user to specify a non-default token. In both cases the interface is such that user must provide the token itself, which is pretty flexible. User can always provide `Sys.getenv("alt_name")` if the token happens to be in an env var.

The `git2r` approach is trickier. What if they haven't stored it in an env var and they just want to provide token? Then we must surround the `git2r` call with `withr::with_envvar()` in order to place it into env var temporarily.

So far it looks like the only usage of `cred_token()` is from me, so it wouldn't affect other people. I left a [comment in `devtools::use_github()`](https://github.com/hadley/devtools/blob/70e1d43bcd325972d3a358fdad544551cb2ff2ef/R/infrastructure-git.R#L119-L122) to switch over once `cred_token()` made it into `git2r` but it's hard to do given the above.

**Comment by jennybc** [comment]
Oh man I now see that I've asked this at least once before (https://github.com/ropensci/git2r/issues/174). Didn't mean to repeat myself. Feel free to consider this "asked and answered".
