### ISSUE TITLE
No commits if git check --depth is used

### ISSUE THREAD

**Issue by nparley** [ropensci/git2r#219]
No commits are given if the repo is cloned using the --depth argument. E.g. 

```
git clone --depth=50 https://github.com/hadley/devtools.git /tmp/devtools/
```

leads to:

```R
> repo <- repository('/tmp/devtools')
> commits(repo)
list()
> repo
Local:    master /tmp/devtools/
Remote:   master @ origin (https://github.com/hadley/devtools.git)
Head:     [2c08890] 2016-01-25: Version bump
```

the latest commits are still there of course:

```
$ git log
commit 2c0889068655e6a8774363de8b413e6be8f9e84e
Author: hadley <h.wickham@gmail.com>
Date:   Mon Jan 25 08:23:05 2016 -0600

    Version bump

commit acae7cb43bc9618d5be8a7932e37bdc7728f8782
Author: hadley <h.wickham@gmail.com>
Date:   Fri Jan 22 09:17:41 2016 -0600

    Final release prep

```

Getting the whole history works:

```
git clone https://github.com/hadley/devtools.git /tmp/devtools_all/
```

gives

```R
> library('git2r')
> repo <- repository('/tmp/devtools_all')
> commits(repo, n=2)
[[1]]
[2c08890] 2016-01-25: Version bump

[[2]]
[acae7cb] 2016-01-22: Final release prep

> repo
Local:    master /tmp/devtools_all/
Remote:   master @ origin (https://github.com/hadley/devtools.git)
Head:     [2c08890] 2016-01-25: Version bump

```

Is there a way to get commits() to show the latest commits even when the whole history is not downloaded?

**Comment by cpsievert** [comment]
+1, [devtools uses this functionality](https://github.com/hadley/devtools/blob/ee33f8c51b2e13c46419807724d56314f0c84460/R/git.R#L7), and travis uses `--depth`.

**Comment by jennybc** [comment]
This is related to #129, where @stewid points out that `libgit2` doesn't support shallow clones. From the issue over on `libgit2` (https://github.com/libgit2/libgit2/issues/3058):

> git can write a file .git/shallow to indicate that the history is cut off at particular commits. We currently do not read this at all and thus libgit2 will regularly fail to work on these repositories with error messages about failing to find objects.

I don't know if it's possible for `git2r` to do some very limited operations on shallow clones, if they are created some other way, e.g. at the command line?

**Comment by stewid** [comment]
A workaround to get the commits from a shallow clone:
 
``` r
library(git2r)

## Open repository
repo <- repository("/tmp/devtools")

## List to hold result
result <- list()

## Get latest commit
x <- lookup(repo, branch_target(head(repo)))

## Repeat until no more parent commits
while(!is.null(x)) {
    result <- append(result, x)

    ## Get parent to commit
    x <- tryCatch(parents(x)[[1]], error = function(e) NULL)
}

## View some commits
head(result)
#> [[1]]
#> [2c08890] 2016-01-25: Version bump
#> 
#> [[2]]
#> [acae7cb] 2016-01-22: Final release prep
#> 
#> [[3]]
#> [7b66221] 2016-01-22: Add check for build-ignored NEWS.md.
#> 
#> [[4]]
#> [a5615c0] 2016-01-22: Merge branch 'master' of github.com:hadley/devtools
#> 
#> [[5]]
#> [cf84917] 2016-01-22: Prepare for release
#> 
#> [[6]]
#> [e241060] 2016-01-21: Revdep checks
```

**Comment by jennybc** [comment]
@stewid That looks very useful! Are you suggesting that the workaround go into `devtools` or will you do something here?

**Comment by stewid** [comment]
I can add the workaround to `git2r::commits` and use it if `is_shallow(repo)` is `TRUE`

**Comment by nparley** [comment]
@stewid thanks for this. I think I will make a pull requests for devtools to use

```R
git2r::branch_target(git2r::head(r))
```
instead of
```R
git2r::commits(r, n = 1)[[1]]@sha
```
when getting the sha of most recent commit
