### ISSUE TITLE
Is it possible to checkout a GitHub Pull Request?

### ISSUE THREAD

**Issue by leeper** [ropensci/git2r#221]
I'm trying to checkout a GitHub pull request using the [instructions here](https://help.github.com/articles/checking-out-pull-requests-locally/) for the command line. Basically:

```
git fetch origin pull/ID/head:BRANCHNAME
```

I am now trying to mimic that using git2r. I can see that the pull request exists as a remote reference using `remote_ls("origin", gitrepo)`, but I don't see any way to actually pull/fetch the PR locally. Am I missing something or is this use of remote references not implemented in git2r?

**Comment by stewid** [comment]
It's not implemented. Currently the `refspec` argument is not used (`NULL`) in the [call](https://github.com/ropensci/git2r/blob/master/src/git2r_remote.c#L162) to [git_remote_fetch](https://libgit2.github.com/libgit2/#HEAD/group/remote/git_remote_fetch). I'm working on it.

**Comment by leeper** [comment]
Sounds good. I'll close this for now, then. Thanks for a great package!

**Comment by stewid** [comment]
I have added the `refspec` argument to `fetch` and the following example

```
## Checking out GitHub pull requests locally
path <- tempfile(pattern="ghit-")
repo <- clone("https://github.com/leeper/ghit", path)
fetch(repo, "origin", refspec = "pull/13/head:refs/heads/BRANCHNAME")
checkout(repo, "BRANCHNAME")
summary(repo)
```

**Comment by leeper** [comment]
Awesome! Thanks!
