### ISSUE TITLE
Issue in the config file for this package

### ISSUE THREAD

**Issue by zaid-golwala** [ropensci/git2r#222]
Hi,

I get following error while installing git2r on R on ubuntu 15.04:

trying URL 'http://cran.rstudio.com/src/contrib/git2r_0.13.1.tar.gz'
Content type 'application/x-gzip' length 1058457 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

* installing *source* package ‘git2r’ ...
** package ‘git2r’ successfully unpacked and MD5 sums checked
checking build system type... tools/config.guess: unable to guess system type

This script, last modified 2012-09-25, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (tools/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2012-09-25

uname -m = ppc64le
uname -r = 3.16.0-23-generic
uname -s = Linux
uname -v = #31-Ubuntu SMP Tue Oct 21 17:55:08 UTC 2014

/usr/bin/uname -p = 
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = ppc64le
UNAME_RELEASE = 3.16.0-23-generic
UNAME_SYSTEM  = Linux
UNAME_VERSION = #31-Ubuntu SMP Tue Oct 21 17:55:08 UTC 2014
configure: error: cannot guess build type; you must specify one
ERROR: configuration failed for package ‘git2r’
* removing ‘/usr/local/lib/R/site-library/git2r’

Can you please update your config file

**Comment by stewid** [comment]
Thanks for reporting the issue.
