### ISSUE TITLE
'git2r' not able install in windows 10 Pro 64bit

### ISSUE THREAD

**Issue by raveendrau** [ropensci/git2r#223]
Hi,

I am using Rstudio, R.3.2.3 and trying to install "git2r", 
Below are the complete messages I have to in console.

Can any one help me out? Thanks

*****************************************************************

install.packages("git2r")
Installing package into ‘C:/Users/ravee/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘git2r’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘git2r’

trying URL 'https://cran.rstudio.com/src/contrib/git2r_0.13.1.tar.gz'
Content type 'application/x-gzip' length 1058457 bytes (1.0 MB)
downloaded 1.0 MB

* installing *source* package 'git2r' ...
** package 'git2r' successfully unpacked and MD5 sums checked
  cannot find zlib files
  attempting to download them
  unpacking zlib files from local320.zip
Archive:  local320.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in local320.zip,
        and cannot find local320.zip.zip, period.

 *** ERROR: unable to find the zlib files

 They must be either in 'src/zlib' or in 'local320.zip'

 You can download local320.zip from
 https://www.stats.ox.ac.uk/pub/Rtools/goodies/multilib/local320.zip

 Another option is to configure the LOCAL_SOFT variable, see:
   https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Windows-packages
   http://www.stats.ox.ac.uk/pub/Rtools/libs.html

Warning: running command 'sh ./configure.win' had status 1
ERROR: configuration failed for package 'git2r'
* removing 'C:/Users/ravee/Documents/R/win-library/3.2/git2r'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\ravee\Documents\R\win-library\3.2" C:\Users\ravee\AppData\Local\Temp\RtmpCacq4O/downloaded_packages/git2r_0.13.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘git2r’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\ravee\AppData\Local\Temp\RtmpCacq4O\downloaded_packages’

**Comment by stewid** [comment]
`git2r` requires `zlib` to build and tries to download that from http://www.stats.ox.ac.uk/pub/Rtools/libs.html. However, `local320.zip` has been replaced with `local323.zip` and therefore the download fails.

I suggest that you install the development version of `git2r` from GitHub using the command line/console

```
git clone https://github.com/ropensci/git2r.git
R CMD INSTALL git2r
```

**Comment by raveendrahadoop** [comment]
Thank you Mr.Stefan,

I have successfully completed 'git clone https://github.com/ropensci/git2r.git' 

But next one 'R CMD INSTALL git2r' , I didn't get exactly what to do. 

can you please let me know how to use the 'install.packages' for downloade source into local disk.

Thank you.

Regards
Ravi

**Comment by stewid** [comment]
Hi @raveendrau 

You are almost done with the installation. First clone the repository and then run the command `R CMD INSTALL git2r`. See the screen capture below how to run the two commands to install `git2r` from source on a Windows machine.

![image](https://cloud.githubusercontent.com/assets/1815965/13389819/f7a368b6-deca-11e5-95e3-59ae8e2ba314.png)
