### ISSUE TITLE
git2r does not allow empty user.email

### ISSUE THREAD

**Issue by jangorecki** [ropensci/git2r#224]
I've got the following error
```
Warning message:

In default_signature(repo) :

  Error in 'git2r_signature_default': Failed to parse signature - Neither `name` nor `email` should contain angle brackets chars.
```

when using following setup
```
  git config user.name "addToDrat"
  git config user.email "<>"
```
The `"<>"` is a valid empty email address.

**Comment by stewid** [comment]
It fails since the angle brackets (' < ' and '>') characters are not allowed, see https://libgit2.github.com/libgit2/#HEAD/group/signature/git_signature_new

**Comment by jangorecki** [comment]
@stewid that is very good justification. I read in one SO the "<>" is valid empty address but if `libgit2` doesn't allow it you can't do much on that. This is quite strange as it works manually. Anyway thanks for feedback.
