### ISSUE TITLE
unable to load shared object

### ISSUE THREAD

**Issue by hurleyLi** [ropensci/git2r#230]
Hi there,

I 'm trying to install git2r under R-3.3.0 in linux, and got similar problem as mentioned in #155 
```
 ** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/frazer01/software/R-3.3.0/lib64/R/library/git2r/libs/git2r.so':
  libssl.so.1.0.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/frazer01/software/R-3.3.0/lib64/R/library/git2r’
```
I have also tried 
```
git clone https://github.com/ropensci/git2r.git
cd git2r
make install
```
and it gave the same error. 

Do you have any idea what might cause this problem?

Thanks!

**Comment by stewid** [comment]
Hi @hurleyLi 

I'm not sure what is going on. Does it work if you reinstall `libssl-dev` with your package manager?

**Comment by hurleyLi** [comment]
It looks like I don't have write permission to a shared tree. I have asked my cluster manager to install it anyway. 

Thanks,

**Comment by puneet336** [comment]
I am facing same issue. Is is possible to install this library without root access?
(R_LIBS points to a installation directory within my $HOME)
command is: R CMD INSTALL git2r_0.16.0.tar.gz

**Comment by mja** [comment]
I had this problem on Scientific Linux 7 and fixed it by creating symlinks in /usr/lib64 from the version naming that gitr wants to the installed version
- `libssl.so.1.0.0 -> libssl.so.1.0.1e`
- `libcrypto.so.1.0.0 -> libcrypto.so.1.0.1e`
