### ISSUE TITLE
 Pluggable backends support?

### ISSUE THREAD

**Issue by scizmeli** [ropensci/git2r#232]
Hi,

Thanks for this wonderful package.
In [this link](http://blog.deveo.com/your-git-repository-in-a-database-pluggable-backends-in-libgit2/), it is mentioned that libgit2 allows to store the repos in places other than the traditional flat files (like in-memory or inside databases).

It might be very useful for the application I am developing.
I wonder if git2r suports these and if it does, how to get started. 

thanks

**Comment by stewid** [comment]
Thanks

No, git2r does not support that.
