### ISSUE TITLE
configure.ac might be broken

### ISSUE THREAD

**Issue by holstius** [ropensci/git2r#236]
On OS X 10.11.5, with Xcode 7.3.1, I was trying to install `git2r` 0.15.0. Grabbed the tarball from `cran.rstudio.com`. 

Specification of `--host` made it work:
```
./configure --host=x86_64-apple-darwin15.5.0
```
... but this didn't:
```
$ ./configure
checking build system type... x86_64-apple-darwin15.5.0
checking host system type... x86_64-apple-darwin15.5.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/dholstius/git2r':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

Sorry I don't have more time to resolve the cause. Hope that's helpful.

**Comment by stewid** [comment]
Thanks for reporting the issue.

**Comment by holstius** [comment]
This was my fault, I think: I had `-bundle` in my `LDFLAGS`, which was preventing the compilation of an *executable* `conftest` on OS X. Don't know why passing `--host-` neutralized that.
