### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by airbj31** [ropensci/git2r#237]
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/bjkim/source/R-3.2.5/library/git2r/libs/git2r.so':
  /home/bjkim/source/R-3.2.5/library/git2r/libs/git2r.so: undefined symbol: curl_easy_send
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/bjkim/source/R-3.2.5/library/git2r’

I've got above errors while installing git2r package.

is there any solution to solve this issue ?

many thanks

**Comment by stewid** [comment]
The function `curl_easy_send` was added to curl version 7.18.2. (https://curl.haxx.se/libcurl/c/curl_easy_send.html). Is it possible that your libcurl version is older than that?

**Comment by airbj31** [comment]
thanks a lot. 
I installed newer version of curl and it solved my problem.

**Comment by stewid** [comment]
Great
