### ISSUE TITLE
List individual files in untracked directories

### ISSUE THREAD

**Issue by sebastian-c** [ropensci/git2r#238]
Hi, I've looked at the documentation and while it's simple to find unstaged changes in a whole repo, it's somewhat harder (impossible?) to do so with individual files. I've opened [this question on StackOverflow](http://stackoverflow.com/q/37317451/1465387) which gives more details.

**Comment by stewid** [comment]
Hi,

Maybe `status(repo)` is what you are looking for

``` r
library(git2r)
repo <- repository("~/projects/git2r/git2r")
status(repo)
#> Untracked files:
#>  Untracked:  man/git-methods.Rd
#>  Untracked:  patches/config.c.patch
#>  Untracked:  patches/odb.c.patch
#> 
#> Unstaged changes:
#>  Modified:   DESCRIPTION
#>  Modified:   NAMESPACE
#> 
#> Staged changes:
#>  New:        R/git-interactive-tool.r
str(status(repo))
#> List of 3
#>  $ staged   :List of 1
#>   ..$ new: chr "R/git-interactive-tool.r"
#>  $ unstaged :List of 2
#>   ..$ modified: chr "DESCRIPTION"
#>   ..$ modified: chr "NAMESPACE"
#>  $ untracked:List of 3
#>   ..$ untracked: chr "man/git-methods.Rd"
#>   ..$ untracked: chr "patches/config.c.patch"
#>   ..$ untracked: chr "patches/odb.c.patch"
#>  - attr(*, "class")= chr "git_status"
```

**Comment by sebastian-c** [comment]
Thanks for replying. That gave me an idea of how to do it - is it possible to expand untracked files? I'm guessing not - a limitations of the api. I'll look into ways to list all tracked files and see if mine are in that group.

**Comment by stewid** [comment]
> is it possible to expand untracked files?

Sorry, I don't understand what you mean.

The `status` method returns a list. Use e.g. `status(repo)$untracked` to get the list of untracked files.

**Comment by sebastian-c** [comment]
Ah, try creating a directory with two files in it. You'll note the the directory is marked as untracked, rather than the files within it. This is pretty standard for git, I think.

**Comment by sebastian-c** [comment]
Ok, better explanation:

Create an untracked directory with two untracked files
```
mkdir untracked
touch untracked/a.txt untracked/b.txt
```

Untracked files as produced by `status` will report this, by default as only the directory:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        untracked/

nothing added to commit but untracked files present (use "git add" to track)
```

This is the same as what happens with, in R:

```
> repo <- repository(".")
> status(repo)
Untracked files:
	Untracked:  untracked/
```

In git, there's a way to expand this:

```
$ git status --untracked-files=all
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        untracked/a.txt
        untracked/b.txt

nothing added to commit but untracked files present (use "git add" to track)
```

There's an option to allow for additional options to `status`. Is there a way to pass this particular option into `status`?

**Comment by stewid** [comment]
Thanks for the suggestion, I have added the option `all_untracked` to the `status` method to list individual files in untracked directories. Could you please give it a try.

**Comment by sebastian-c** [comment]
Ok, tried it out, got an error:

```
> repo <- repository(".")
> status(repo)
Error in .Call(git2r_status_list, repo, staged, unstaged, untracked, all_untracked,  : 
  Incorrect number of arguments (6), expecting 5 for 'git2r_status_list'
> status(repo, all_untracked = TRUE)
Error in .Call(git2r_status_list, repo, staged, unstaged, untracked, all_untracked,  : 
  Incorrect number of arguments (6), expecting 5 for 'git2r_status_list'
```

**Comment by stewid** [comment]
Is it possible that the C code wasn't recompiled? I get the following output when I try your example

```
> library(git2r)
> repo <- repository(".")
> status(repo)
Untracked files:
	Untracked:  untracked/
```
```
> status(repo, all_untracked = TRUE)
Untracked files:
	Untracked:  untracked/a.txt
	Untracked:  untracked/b.txt
```

**Comment by sebastian-c** [comment]
I've been installing it using `devtools::install_github`. I'm going to uninstall and reinstall the package and if that doesn't work, I'll try installing it manually. If that still doesn't work, I'll try installing it on Ubuntu (I'm on Windows at the moment).

**Comment by sebastian-c** [comment]
Ok, tried again after uninstalling before reinstalling the package and it worked perfectly!

**Comment by sebastian-c** [comment]
Ok, I think that this issue is solved. Feel free to close it if you agree.

**Comment by stewid** [comment]
Thanks

**Comment by sebastian-c** [comment]
Thank you for taking the time to look at my issue :smile:
