### ISSUE TITLE
put NEWS bits in releases

### ISSUE THREAD

**Issue by sckott** [ropensci/git2r#239]
hey @stewid  - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  
- you already keep a `NEWS` file, thanks!
- thanks for git tagging!
- Could you please use the [releases tab](https://github.com/ropensci/git2r/releases) on this repo to include the associated NEWS items for each tag/version ? thanks 😄

**Comment by stewid** [comment]
Hi @sckott,
I submitted a new version (v0.16.0) to CRAN today and added the NEWS items for each release.

Cheers

**Comment by sckott** [comment]
@stewid thanks very much!
