### ISSUE TITLE
wrong password in push kill RStudio

### ISSUE THREAD

**Issue by MarcinKosinski** [ropensci/git2r#241]
@pbiecek have checked that wrong password in `git2r::push` that is inside other function (let's have [archivist.github::createGitHubRepo](https://github.com/MarcinKosinski/archivist.github/blob/master/R/createGitHubRepo.R#L233)) kills RStudio without any informative message. Maybe there is a way to check the password in advance before it will be used in `push` ?

Move from here https://github.com/MarcinKosinski/archivist.github/issues/12

**Comment by stewid** [comment]
Thanks for reporting the issue.

Does the Rstudio session freeze or crash when you push with the wrong password?
