### ISSUE TITLE
Error at compiling

### ISSUE THREAD

**Issue by awakumaya** [ropensci/git2r#242]
I failed git2r on R installed using home-brew as follows.

> install.packages("git2r",dependencies=TRUE)
> Installing package into ‘/usr/local/lib/R/3.3/site-library’
> (as ‘lib’ is unspecified)
> --- Please select a CRAN mirror for use in this session ---
> HTTPS CRAN mirror

 1: 0-Cloud [https]                2: Algeria [https]
 3: Austria [https]                4: Belgium (Ghent) [https]
 5: Chile [https]                  6: China (Beijing 4) [https]
 7: Colombia (Cali) [https]        8: France (Lyon 1) [https]
 9: France (Lyon 2) [https]       10: France (Paris 2) [https]
11: Germany (Münster) [https]     12: Iceland [https]
13: Italy (Padua) [https]         14: Japan (Tokyo) [https]
15: Malaysia [https]              16: Mexico (Mexico City) [https]
17: New Zealand [https]           18: Russia (Moscow) [https]
19: Serbia [https]                20: Spain (A Coruña) [https]
21: Spain (Madrid) [https]        22: Switzerland [https]
23: UK (Bristol) [https]          24: UK (Cambridge) [https]
25: USA (CA 1) [https]            26: USA (KS) [https]
27: USA (MI 1) [https]            28: USA (TN) [https]
29: USA (TX) [https]              30: USA (WA) [https]
31: (HTTP mirrors)

Selection: 14
trying URL 'https://cran.ism.ac.jp/src/contrib/git2r_0.15.0.tar.gz'
# Content type 'application/x-gzip' length 1084978 bytes (1.0 MB)

downloaded 1.0 MB
- installing _source_ package ‘git2r’ ...
  *\* package ‘git2r’ successfully unpacked and MD5 sums checked
  checking build system type... x86_64-apple-darwin15.5.0
  checking host system type... x86_64-apple-darwin15.5.0
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... configure: error: in `/private/var/folders/st/v83wlc695_dg_17j4_b2dns00000gn/T/RtmpGSIB5V/R.INSTALLaf106a3564f7/git2r':
  configure: error: cannot run C compiled programs.
  If you meant to cross compile, use`--host'.
  See `config.log' for more details
  ERROR: configuration failed for package ‘git2r’
- removing ‘/usr/local/lib/R/3.3/site-library/git2r’

The downloaded source packages are in
    ‘/private/var/folders/st/v83wlc695_dg_17j4_b2dns00000gn/T/Rtmp4M7cox/downloaded_packages’
Warning message:
In install.packages("git2r", dependencies = TRUE) :
  installation of package ‘git2r’ had non-zero exit status

My session info is as follows:

> sessionInfo()
> R version 3.3.0 (2016-05-03)
> Platform: x86_64-apple-darwin15.5.0 (64-bit)
> Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] tools_3.3.0

And I tried following command:
git clone https://github.com/ropensci/git2r.git
R CMD INSTALL git2r

But still failed.

**Comment by sanmai-NL** [comment]
Perhaps this is our issue:
```
./configure: 5932: test: x8: unexpected operator
./configure: 5934: test: x8: unexpected operator
configure: error: in `/tmp/RtmpWAzK7L/R.INSTALL4df11a9ccba9/git2r':
configure: error: Unsupported architecture
```
```
#$> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=nl_NL.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=nl_NL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.0
```

**Comment by stewid** [comment]
@awakumaya 

Maybe the solution in #236 works for you?
