### ISSUE TITLE
git rm

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#247]
Would you be willing to expose [`git_index_remove`](https://libgit2.github.com/libgit2/#HEAD/group/index/git_index_remove) so that `git2r` supports [`git rm`](https://git-scm.com/docs/git-rm), meaning "delete file from the working directory and also stage the deletion"? I can't tell from the very terse documentation if the `stage` argument is useful, i.e. does it maybe relate to `git rm --force`? If so, that would be nice as an additional argument.

**Comment by jennybc** [comment]
WAIT now I see `git2r::rm_file()`, which I believe is exactly this. In which case my only question is whether the `stage` argument of `git_index_remove` does anything worth exposing on the R side.

**Comment by jennybc** [comment]
I have a specific hope that `stage` can be used to specify whether the removal is from working tree or only from the index. Because I don't currently know how to use `git2r` to un-stage in the (admittedly very special) case where there aren't yet any commits. `git2r::reset()` currently requires a commit.

Here's what I mean:

``` r
library(git2r)

path <- tempfile("git-unstage-example-")
dir.create(path)
gr <- init(path)
owd <- setwd(path)
write("blah", file.path(path, "unstage-me.txt"))
status(gr)
#> Untracked files:
#>  Untracked:  unstage-me.txt
add(gr, "unstage-me.txt")
status(gr)
#> Staged changes:
#>  New:        unstage-me.txt
## here's how resetting could unfold
##   * get HEAD
##   * ... get associated commit
##   * mixed reset to that commit
## but this doesn't work after init but prior to any commits
(h <- head(gr))
#> NULL
h_commit <- lookup(gr, sha = branch_target(h))
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'branch_target' for signature '"NULL"'
reset(h_commit, reset_type = "mixed")
#> Error in reset(h_commit, reset_type = "mixed"): object 'h_commit' not found
setwd(owd)
```

This comment on a SO answer highlights this rare case when you can't use `git reset` to unstage (related to #250, which is about unstaging specific paths):

http://stackoverflow.com/questions/6919121/why-are-there-2-ways-to-unstage-a-file-in-git#comment39508015_6919749

**Comment by stewid** [comment]
This is an example to illustrate that it is now possible to reset a file from a repository where there aren't yet any commits
 
``` r
library(git2r)                          
                                        
path <- tempfile("git-unstage-example-")
dir.create(path)                        
(gr <- init(path))                      
#> Local:    /tmp/RtmpPtbc4R/git-unstage-example-37ce7e6c3faa/
#> Head:     nothing commited (yet)
owd <- setwd(path)                      
write("blah", "unstage-me.txt")         
status(gr)                              
#> Untracked files:
#>  Untracked:  unstage-me.txt
add(gr, "unstage-me.txt")               
status(gr)                              
#> Staged changes:
#>  New:        unstage-me.txt
reset(gr, path = "unstage-me.txt")      
status(gr)                              
#> Untracked files:
#>  Untracked:  unstage-me.txt
gr                                      
#> Local:    /tmp/RtmpPtbc4R/git-unstage-example-37ce7e6c3faa/
#> Head:     nothing commited (yet)
setwd(owd)                              
```
