### ISSUE TITLE
Is it easy to return more info after staging or committing?

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#248]
Would it be "easy" for `git2r` to return file paths actually affected by staging or committing? Does libgit2 return that info? If so, `git2r` could pass it through as the return value.

It's not necessarily the paths you pass in. These could be shell globs or ignored files. Or unmodified paths. There are a lot of reasons why the paths actually staged or committed could differ from those requested.

I can obviously do some pre- and post-work to determine this for myself but

  * it would be ideal if libgit2 provided this and `git2r` just exposed it
  * it would be available to more people if it happened here

**Comment by stewid** [comment]
I'm not aware of any functions in libgit2 that provide this directly so it requires some pre- and post-work. The `status` method returns a list with staged, unstaged, untracked and ignored files.  The `git_diff` object contains a list with `git_diff_file` objects with the file path, see below.

``` r
library(git2r)

files_in_commit <- function(commit) {
    ## Take the diff to each parent and extract the files
    unlist(lapply(parents(commit), function(p) {
        d <- diff(tree(p), tree(commit))
        sapply(d@files, slot, "new_file")
    }))
}

## Open a repository
repo <- repository("~/projects/git2r/git2r")

## Get the files in the last commit
files_in_commit(commits(repo, n = 1)[[1]])
#> [1] "R/libgit2.r"
#> [2] "src/libgit2/include/git2/repository.h"
#> [3] "src/libgit2/src/repository.c"
```

**Comment by jennybc** [comment]
OK thanks. That answers my question.
