### ISSUE TITLE
reflog() is very chatty

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#249]
The behaviour of `reflog()` seems a bit nonstandard. It feels like show/print is baked into the act of retrieving the reflog. So, even if I assign the reflog to an object or extract a single component, the entire object is shown.

``` r
## this is the only call where I expect to see full reflog printed to screen
reflog(gr)
#> [77c8a79] HEAD@{0}: reset: moving to 77c8a7994d63c20d4ec9dbcb925f3a857ceed57a
#> [6bded0e] HEAD@{1}: commit: second commit
#> [77c8a79] HEAD@{2}: commit (initial): first commit
class(reflog(gr))
#> [77c8a79] HEAD@{0}: reset: moving to 77c8a7994d63c20d4ec9dbcb925f3a857ceed57a
#> [6bded0e] HEAD@{1}: commit: second commit
#> [77c8a79] HEAD@{2}: commit (initial): first commit
#> [1] "list"
reflog(gr)[[1]]
#> [77c8a79] HEAD@{0}: reset: moving to 77c8a7994d63c20d4ec9dbcb925f3a857ceed57a
#> [6bded0e] HEAD@{1}: commit: second commit
#> [77c8a79] HEAD@{2}: commit (initial): first commit
#> [77c8a79] HEAD@{0}: reset: moving to 77c8a7994d63c20d4ec9dbcb925f3a857ceed57a
rl <- reflog(gr)
#> [77c8a79] HEAD@{0}: reset: moving to 77c8a7994d63c20d4ec9dbcb925f3a857ceed57a
#> [6bded0e] HEAD@{1}: commit: second commit
#> [77c8a79] HEAD@{2}: commit (initial): first commit
```

I see that `verbose` controls this behaviour. Perhaps it should default to `FALSE`? But then my first call would not print the object, which would also be a surprise. Is this a design predicament because there's no class/methods for the list of reflog entries, but rather only for the individual entries?

**Comment by stewid** [comment]
Thanks for reporting this, I have separated retrieving the reflog from printing the reflog entries.

**Comment by jennybc** [comment]
Thanks for the speedy service!
