### ISSUE TITLE
Expose git_index_remove_bypath

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#250]
<https://libgit2.github.com/libgit2/#HEAD/group/index/git_index_remove_bypath>

With command line Git, it's possible to undo `git add` for specific paths. To quote the [`git reset` documentation](https://git-scm.com/docs/git-reset):

> `git reset <paths>` is the opposite of `git add <paths>`

This doesn't currently seem possible with `git2r`. I think the only way to reset the index to current `HEAD` is to use `reset()`, which affects all staged paths.

Do I understand correctly? If so, what do you think of exposing `git_index_remove_bypath` to enable selective resetting?

**Comment by stewid** [comment]
I have added `index_remove_bypath`. I was already using `git_index_remove_bypath` internally, so it was easy to expose the function. Please give it a try.
