### ISSUE TITLE
interactive passphraseinput in case of passphrase needed

### ISSUE THREAD

**Issue by petermeissner** [ropensci/git2r#252]
**motivation**

It is said (by the internet and people seeming to know more about that stuff than I) that using a passphrase to secure ssh-key is a proper way to go - so capturing my computer does not mean caputring my Github and Server and ... as well. So I use a passphrase. 

Now git2r can handle the usage of passphrases perfectly fine.

But to use it I have to write it down in exact vanilla lettering - which contradicts the idea to use a passphrase in the first place - right?

**vision / goal**

Now wouldn't it be great to have a pop-up-window asking for the passphrase interactivaly and forgetting it again the moment I the function is done or my R-session is closed? 

**solution ideas / things tried out so far**

For my own purposes I have hacked together some wrappers that generate the credentials on the fly. The passphrase input is done by using `rstudioapi::askForPassword()` function since I use Rstudio anyways - works very well. 

To get maximal compatibility one might instead use the [getPass](https://github.com/wrathematics/getPass) package which will use afore mentioned rstudioapi function if availible but can fall back to tcltk (which ships with R) or even manages to let you type in passwords masked by sparkling stars on the commandline (yes, Windows too).

Looking fo a way to check if keys are encrypted [I found that this is stated in the private key file](http://unix.stackexchange.com/a/528/136792). A function to check for encryption could look something like that:

```r 
ssh_key_needs_passphrase <- function(privatekey = "~/.ssh/id_rsa"){
  private_content    <- readLines(privatekey, n=3)
  contains_encrypted <- grepl("encrypted",  private_content , ignore.case = TRUE)
  return(
    any(contains_encrypted)
  )
}
```

Maybe one can build it into `cred_ssh_key()` asking for a passphrase via `getPass()` if passphrase is not set or if it is NULL ... but than internal handling of credentials has maybe to rewritten. But `cred_ssh_key()` could return NULL if credentials are not needed? ... 

```r
cred_ssh_key <- 
  function (publickey = "~/.ssh/id_rsa.pub", privatekey = "~/.ssh/id_rsa", 
            passphrase = character(0)) 
  {
    if( !ssh_key_needs_passphrase(privatekey) ){
      return(NULL)
    }else{
      if( length(passphrase)==0 ){
        passphrase <- getPass::getPass()
      }
      
      new(
        "cred_ssh_key", 
        publickey = normalizePath(publickey, mustWork = TRUE), 
        privatekey = normalizePath(privatekey, mustWork = TRUE), 
        passphrase = passphrase
      )
    }
  }
```

**conclusion**

I think interactive passphrase typing in is a thing which should really be provided by the package - dont let people store there passphrase in their R-scripts. I am not sure though, how to incorporate this functionality smoothly into the package's functions.

**Comment by stewid** [comment]
Hi, thanks for the suggestion, I agree that this could be a nice feature to add. Let me come back in a day or two when I have more time.
Cheers

**Comment by stewid** [comment]
Apologize for the delay.

The cred_ssh_key function cannot return NULL, since that means (internally) to ask the ssh-agent for the credentials (https://github.com/ropensci/git2r/blob/master/src/git2r_cred.c#L232)

I think your solution looks fine. I added the requireNamespace statement so that getPass can be a suggested package. Could you please test if it still works and create a pull request?

```
cred_ssh_key <-  function (publickey = "~/.ssh/id_rsa.pub",
                           privatekey = "~/.ssh/id_rsa", 
                           passphrase = character(0))
{
    publickey = normalizePath(publickey, mustWork = TRUE)
    privatekey = normalizePath(privatekey, mustWork = TRUE)

    if (length(passphrase) == 0) {
        if (ssh_key_needs_passphrase(privatekey)) {
            if (requireNamespace("getPass", quietly = TRUE)) {
                passphrase <- getPass::getPass()
            }
        }
    }

    new("cred_ssh_key",
        publickey  = publickey,
        privatekey = privatekey,
        passphrase = passphrase)
}
```

Thanks

**Comment by petermeissner** [comment]
ok, will do ...

Just so that I get that right in my head... 

- all functions that might need credentials have NULL as default for credentials (e.g. pull, push, ...)
- NULL triggers asking an agent for getting things right
- but if I add a simple call to cred_ssh_key() without passphrase getPass() will be triggered - if the package is availible

Right? Cool.

**Comment by stewid** [comment]
Yes that's correct.

**Comment by petermeissner** [comment]
#254
