### ISSUE TITLE
Checkout Single File Given Commit and Path

### ISSUE THREAD

**Issue by rtaph** [ropensci/git2r#255]
Hi there,

Thanks for the great package.

Is it possible to checkout a single file given the file path and commit (`git_commit` object)? I am looking at #181 but this only seems to introduce a method where the object passed into the function is a repository. I don't understand where the specific commit for the file comes into the picture.

For example, if I have the following treeish:

```r
c1   <- lookup(repo, "abcd936")
class(c1)
#> [1] "git_commit"
#> attr(,"package")
#> [1] "git2r"
```

...it would be great to be able to do

```r
checkout(c1, path = "abcd.txt")
```

Is this possible? What am I missing?

**Comment by stewid** [comment]
Thanks.

No, it's not possible to checkout a file, but you can view the content with
```
content(tree(lookup(repo, "abcd936"))["abcd.txt"])
```

**Comment by rtaph** [comment]
Brilliant. Thank you!
