### ISSUE TITLE
Git Log a File

### ISSUE THREAD

**Issue by rtaph** [ropensci/git2r#256]
Hello,

Using git2r, is it possible to log a single file in order to reveal the commit history on that file?

Thanks,

**Comment by stewid** [comment]
Please try `odb_blobs` to list all blobs reachable from the commits in the object database as a `data.frame` and then filter the single file.

**Comment by rtaph** [comment]
Thanks @stewid. Your solution works perfectly for my purposes.

Follow-up question: do I understand correctly that there is no easy way to to follow documents through name changes with `git2r`?

**Comment by stewid** [comment]
That is correct. Maybe you can combine the tree and diff functionality to achieve that.

**Comment by rtaph** [comment]
Alright! Thank you for your help 👍

**Comment by jdblischak** [comment]
Quick update. The argument `path` was added to `git2r::commits()` in git2r 0.26.0 (PR #372). It will return all the commits that touched a specific file (which is faster than generating `odb_blobs()` of the entire Git repo).

However, it does have the same limitation in that it does not follow file renames. Thus it is equivalent to `git log --no-follow`.
