### ISSUE TITLE
Can't install in root, but success in openuser (centos7)

### ISSUE THREAD

**Issue by SraRod** [ropensci/git2r#258]
Hello, I try to install git2r in my Centos 7.
I success by openuser,  but root is not work.

The following is (a part of) error message:
```
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/lib64/R/library/git2r/libs/git2r.so':
  libssl.so.1.0.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing â/usr/lib64/R/library/git2râ

The downloaded source packages are in
        â/tmp/RtmpskOCRt/downloaded_packagesâ
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("git2r") :
  installation of package âgit2râ had non-zero exit status
```

I searched many method to solve this problem,
include install some program maybe needed. (But I don't realize each program, these just be gathered from many website.
```
yum install gcc gcc-c++ gcc-gfortran pcre-devel tcl-devel zlib-devel bzip2-devel readline-devel libXt-devel tk-devel tetex-latex gnutls-devel.x86_64 libcurl libcurl-devel libxml2 libxml2-devel openssl openssl-devel
``` 
I success on openuser, so I think these programs are not problems.

Then I also try install by source in github (in root)
```
git clone https://github.com/ropensci/git2r
R CMD INSTALL git2r
```
But it still not work.

Because I install git2r for run devtools, I can't try *install_gihub* in *devtools*.

Hope someone can help me to solve this problem, thanks!

**Comment by SraRod** [comment]
Hello, everybody! 
I think the cause that maybe is a Permissions problem.
I enter R environment using ```R``` in root user, then this problem occurs.
But I try ```sudo R``` to enter R in root user, there is no any problems occur.

**Comment by elbamos** [comment]
I see the same thing as srarod.  This doesn't seem to be a permission issue.  It seems to be a paths issue.
