### ISSUE TITLE
Unsupported architecture  error

### ISSUE THREAD

**Issue by A1dnoah** [ropensci/git2r#268]
I read your tutorial about the qusetion openssl(https://github.com/ropensci/git2r/issues/204), but when I tried the command  
R CMD INSTALL --configure-args='--with-libssl-include=/home/zhangwei/software/openssl/include --with-libssl-lib=/home/zhangwei/software/openssl/lib' git2r_0.16.0.tar.gz
it report 
configure: error: in `/tmp/RtmptTFhPl/R.INSTALL6b1b76dcf2a9/git2r':
configure: error: Unsupported architecture
See `config.log' for more details
ERROR: configuration failed for package ‘git2r’
* removing ‘/usr/local/lib64/R/library/git2r’
I also read this https://github.com/ropensci/git2r/issues/245, but it does not helps.
I run R 3.3.2 on centos7.

**Comment by jooolia** [comment]
Are there any ideas on this? I am also having the same problem on Centos 6.5 with R 3.1.2.

Thanks! Julia

**Comment by stewid** [comment]
I'm not sure why the configuration fails, but I have made a small change to the configure script that maybe fix the problem. Could you please try to install the latest version from GitHub .

**Comment by stewid** [comment]
Fixed in commit a36e9d8ca5417d6ae82fada0b19191160512c9e5, see #288.

**Comment by jooolia** [comment]
Thanks! Will give it a go.
