### ISSUE TITLE
New release needed to build against LibreSSL

### ISSUE THREAD

**Issue by fenwanderer** [ropensci/git2r#272]
Commit a03562d enables libgit2 to build against LibreSSL (see https://github.com/libgit2/libgit2/pull/4043).  Until it is incorporated into a new git2r release and pushed out to CRAN, attempts to install v0.18.0 on systems with LibreSSL will fail:

```
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/lib/R/library/git2r/libs/git2r.so':
  Error relocating /usr/lib/R/library/git2r/libs/git2r.so: BIO_set_data: symbol not found
Error: loading failed
Execution halted
ERROR: loading failed
```

**Comment by artemklevtsov** [comment]
Confirm this: https://gitlab.com/artemklevtsov/r-alpine/builds/13232206

**Comment by stewid** [comment]
A new version (v0.19.0) is now on CRAN.
