### ISSUE TITLE
how to sort git2r objects by time ?

### ISSUE THREAD

**Issue by kforner** [ropensci/git2r#276]
[My use case is still to sort tags() by date].

I saw the `when()` generic that is able to fetch the time as a character string on any type of git2r object. The problem is that it can not be used to sort the objects by time for instance. 
Is there a corresponding accessor generic that I missed that returns the date ? 

I figured out that I can use as.POSIXct(when(object)) but it seems fragile. Is this the right way ?

Thanks.

**Comment by stewid** [comment]
You can convert directly from the git2r git_time object to POSIXct (https://github.com/ropensci/git2r/blob/master/R/time.r#L25)
  
```
r <- repository("/path/to/git2r/")
as(tags(r)[["v0.18.0"]]@tagger@when, "POSIXct")
[1] "2017-01-01 22:27:00 GMT"
```
