### ISSUE TITLE
Interface to git reset

### ISSUE THREAD

**Issue by aoles** [ropensci/git2r#281]
Hi,
I'm trying to replicate in R the following sequence of console commands.

```
cd DIR
git init
git remote add origin PATH/TO/REPO
git fetch
git reset origin/master
```
So far I've got,
```r
repo <- init("DIR")
remote_add(repo, "origin", "PATH/TO/REPO")
fetch(repo, "origin")
```
but got stuck with the last command `git reset origin/master` and didn't quite figure out how it can be translated into a call to the *git2r*'s `reset` method. But maybe I'm missing something here. In case you're wondering, my particular use case is described by [this scenario](http://stackoverflow.com/q/2411031/2792099).

Any advice is greatly appreciated!

Cheers,
Andrzej

**Comment by stewid** [comment]
Here are some examples of how git2r reset can be used.

```
library(git2r)

## Create a directory in tempdir
path <- tempfile(pattern="git2r-")
dir.create(path)

## Initialize a repository
repo <- init(path)
config(repo, user.name="Alice", user.email="alice@example.org")

## Create a file
writeLines("Hello world!", file.path(path, "test-1.txt"))

## add and commit
add(repo, 'test-1.txt')
commit_1 <- commit(repo, "Commit message")

## Make one more commit
writeLines(c("Hello world!", "HELLO WORLD!"), file.path(path, "test-1.txt"))
add(repo, 'test-1.txt')
commit(repo, "Next commit message")

## Create one more file
writeLines("Hello world!", file.path(path, "test-2.txt"))

## 'soft' reset to first commit
reset(commit_1)
status(repo)

## 'mixed' reset to first commit
commit(repo, "Next commit message")
reset(commit_1, "mixed")
status(repo)

## 'hard' reset to first commit
add(repo, 'test-1.txt')
commit(repo, "Next commit message")
reset(commit_1, "hard")
status(repo)
```

**Comment by aoles** [comment]
Hi Stefan,
thank you for getting back to me with the examples. Actually, I read through the man pages beforehand, but didn't find a method corresponding to the git command resetting the local branch to upstream, i.e. `git reset origin/master`. So I was wondering whether this is possible from the R interface? I was hoping for some advice on a clever way of achieving this.

Now I've also found out that there is another and probably better way of achieving the same result as with my original sequence of git commands:

```
git clone --no-checkout PATH/TO/REPO .tmp
mv .tmp/.git .
rm -rf .tmp
git reset
```
But this time I'm stuck right at the beginning as I have no idea how to pass the `--no-checkout` option to `clone`. Again, is this possible from *git2r*'s interface?

I would really appreciate some help with either of the approaches. If these options are not yet implemented in your package, please let me know whether there is anything I could help you with in order to get this working.

Cheers,
Andrzej

**Comment by aoles** [comment]
I had a look into enabling in `git2r::clone` the command line option `--no-checkout` and came up with the following implementation https://github.com/ropensci/git2r/pull/282/commits/fd0f2a28b52d250de67a295e3407a02174ad7714. Using the updated `clone` method I'm now able to achieve my original goal without the need of doing `git reset origin/master`.

I would like to use this approach in an R package I'm developing, so it would be great if you would kindly consider my pull request https://github.com/ropensci/git2r/pull/282.

Thanks,
Andrzej
