### ISSUE TITLE
What dependency do I need to enable threads?

### ISSUE THREAD

**Issue by cboettig** [ropensci/git2r#285]
Hi @stewid ,

Sorry to bug you again, probably an easy one this time.  What dependency do I need on a debian system to get git2r to build with support for threads?  Thanks!

**Comment by stewid** [comment]
Although threads are supported by [libgit2](https://github.com/libgit2/libgit2/blob/master/THREADING.md), there is currently no way to enable that feature when building git2r, in order not to get additional complexity. 

Do you have a use case that would benefit from threads?

**Comment by cboettig** [comment]
@stewid ok, glad I'm not missing anything trivial. Yeah, the combination of the `gh` package and `git2r` make it easy to script lots of git commands which often results in scenarios where threading would be nice, but it's certainly not mission critical.
