### ISSUE TITLE
Expose flag GIT_MERGE_FAIL_ON_CONFLICT

### ISSUE THREAD

**Issue by jdblischak** [ropensci/git2r#293]
Would it be possible to expose the libgit2 flag `GIT_MERGE_FAIL_ON_CONFLICT`as an argument to `git2r::merge`? From its [libgit2 API entry](https://libgit2.github.com/libgit2/#HEAD/type/git_merge_flag_t):

> If a conflict occurs, exit immediately instead of attempting to continue resolving conflicts. The merge operation will fail with GIT_EMERGECONFLICT and no index will be returned.

**Comment by stewid** [comment]
I have added `fail` to merge

**Comment by jdblischak** [comment]
Thanks so much for implementing this, @stewid! I ran your unit tests, and everything looks good.
