### ISSUE TITLE
 error authenticating: no auth sock variable

### ISSUE THREAD

**Issue by itcarroll** [ropensci/git2r#296]
Help for the `credentials` argument says to leave it NULL to use and query the ssh-agent, but I don't think that's happening for me.

Here's an example using a github repo that I own:
```
pkg <- file.path(tempdir(), 'pkg')
system2('git', args = c('clone', 'git@github.com:sesync-ci/rslurm.git', pkg))
repo <- git2r::repository(pkg)
git2r::pull(repo)
```
returns
```
Error in fetch(repo = repo, name = branch_remote_name(upstream_branch),  : 
  Error in 'git2r_remote_fetch': error authenticating: no auth sock variable
```

Meanwhile, using `git pull` in a terminal works fine. If there is a set-up step for ssh-agent, I cannot find it explained and do not know about ssh-agents.

**Comment by pat-s** [comment]
Is there meanwhile any solution to this?

**Comment by djm158** [comment]
Does `Sys.getenv()` return any of the following?

- `SSH_AGENT_PID`
- `SSH_AUTH_SOCK`
- `SSH_CLIENT`
- `SSH_TTY`

I usually have to run the following to get ssh to work:

eval \`ssh-agent\`
ssh-add

assuming your public/private keys are in `~/.ssh/id_rsa.pub` and ~/.ssh/id_ras`, respectively.

**Comment by jdblischak** [comment]
A hacky workaround to define the environment variable `SSH_AUTH_SOCK` in your R session is to create `~/.Rprofile` with the following lines:

```
ssh_auth_sock <- system("echo $SSH_AUTH_SOCK", intern = TRUE)
Sys.setenv(SSH_AUTH_SOCK = ssh_auth_sock)
```

This code will be executed every time R is started, and it will read the value of `SSH_AUTH_SOCK` defined in your bash session.

And for what it's worth, on my Ubuntu 17.10 setup, `SSU_AUTH_SOCK` is defined both in bash and in R, so it is possible for R to recognize the ssh-agent. I followed the [GitHub instructions](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) for setting up SSH keys.

**Comment by pat-s** [comment]
Indeed, `SSH_AUTH_SOCK` was not defined. Solved it on Arch by following the [wiki instructions](https://wiki.archlinux.org/index.php/SSH_keys#Start_ssh-agent_with_systemd_user). 
I thought initially everything was fine as I used ssh with github all the time but there seem to be differences.

**Comment by LiamKarlMitchell** [comment]
For anyone else who happens to be googling this issue for gitkraken on wsl2
djm158's commands fixed it for me on Ubuntu WSL2 with gitkraken.

**Comment by itcarroll** [comment]
Closing, b/c not a git2r issue. Useful info above tho.

**Comment by LoopLupe** [comment]
> ssh-add

very userful, thanks
