### ISSUE TITLE
fetch() causes session to hang

### ISSUE THREAD

**Issue by jemus42** [ropensci/git2r#298]
I ran into this issue while running `devtools::release()`, which runs various checks.  
One of those being `devtools:::git_sync_status`, where `git2r` is used to update the repository.  
Recreating the function step by step I got stuck on the following line: `git2r::fetch(r, git2r::branch_remote_name(upstream))` which takes ages, makes my fans spin up and so far I have yet to see it actually complete.

Steps to reproduce:

```
git clone git@github.com:tadaadata/tadaatoolbox.git
cd tadaatoolbox
R
```
then in R, I executed the lines of `devtools:::git_sync_status`
```
path = "."
check_ahead = TRUE
check_behind = TRUE

r <- git2r::repository(path, discover = TRUE)
r_head <- git2r::head(r)
if (!methods::is(r_head, "git_branch")) {
  stop("HEAD is not a branch", call. = FALSE)
}
upstream <- git2r::branch_get_upstream(r_head)
if (is.null(upstream)) {
  stop("No upstream branch", call. = FALSE)
}
git2r::fetch(r, git2r::branch_remote_name(upstream))
```

At this point the R session just… hangs. I have no idea how to debug this further, besides checking that `git fetch origin` in a shell functions normally. Other than that, I've been working with/on that repository at that URL for months now, and so far I have no reason to assume that the repository is in some way funky.  
Oh, and the issue arises both in RStudio (which then causes RStudio to crash when I try to cancel the current command) and in raw R in a shell.

Version info:
- OS: macOS 10.12.6
- R 3.4.2
- git2r 0.19.0
- git version 2.15.0

**Comment by stewid** [comment]
I have submitted a new version 0.21 to CRAN. Could you please check if it works with the new version, or if that also causes session to hang.

Thanks

**Comment by jemus42** [comment]
I tried re-checking but right now I only get the following error in 0.20 and the current 0.21:

```
Error in git2r::fetch(r, git2r::branch_remote_name(upstream)) : 
  Error in 'git2r_remote_fetch': error authenticating:
```

With no further explanation, which has me a little baffled since I don't know what might have changed with my setup. I have the `GITHUB_PAT` environment variable set to a valid token.
So... I can't really check the issue at hand without this devolving into a separate issue thread.

**Comment by jdblischak** [comment]
> I have the `GITHUB_PAT` environment variable set to a valid token.

@jemus42 git2r doesn't use the `GITHUB_PAT` environment variable. It will use the remote URL you have configured, which in this case is `git@github.com:tadaadata/tadaatoolbox.git`.

You are using SSH for authentication. Do your SSH keys have a passphrase? That might be the cause of the error. See related discussion in https://github.com/jdblischak/workflowr/pull/203.
