### ISSUE TITLE
adding functions to work with git data repositories?

### ISSUE THREAD

**Issue by ThierryO** [ropensci/git2r#301]
I use git to to create data repositories. The idea is to store `data.frames` as tab delimited files in a git repository. I wrote some utility functions to make this easier, e.g. [`read_delim_git()`](https://github.com/inbo/n2khelper/blob/master/R/read_delim_git.R), [`write_delim_git()`](https://github.com/inbo/n2khelper/blob/master/R/write_delim_git.R), [`list_files_git()`](https://github.com/inbo/n2khelper/blob/master/R/list_files_git.R) and [`remove_files_git()`](https://github.com/inbo/n2khelper/blob/master/R/remove_files_git.R). 

Would you consider a pull request that adds such functionality to `git2r`?

**Comment by stewid** [comment]
@ThierryO that sounds like a great functionality to have in `git2r`. Please go ahead and create a pull request.

Thanks

**Comment by ThierryO** [comment]
OK. I'll create a pull request in the upcoming weeks.

**Comment by ThierryO** [comment]
This functionality is now available as a dedicated package: [git2rdata](https://cloud.r-project.org/package=git2rdata)
