### ISSUE TITLE
gitr2 not installing R 3.4.2 / RStudio 1.1.383 / Conda 1.6.9

### ISSUE THREAD

**Issue by mdacampora** [ropensci/git2r#302]
I have checked some of the other issue posts to no avail. This is preventing me from installing devtools and a few other libraries I will need.

I am running Linux Mint 18.3 / Ubuntu 16.04

> install.packages('git2r')
trying URL 'https://cran.rstudio.com/src/contrib/git2r_0.19.0.tar.gz'
Content type 'application/x-gzip' length 1155950 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

* installing *source* package ‘git2r’ ...
** package ‘git2r’ successfully unpacked and MD5 sums checked
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /lib/cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... no
checking for sys/stat.h... no
checking for stdlib.h... no
checking for string.h... no
checking for memory.h... no
checking for strings.h... no
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... no
checking size of void*... 0
configure: error: in `/tmp/Rtmp4BN45x/R.INSTALL7a5256d0566f/git2r':
configure: error: Unsupported architecture
See `config.log' for more details
ERROR: configuration failed for package ‘git2r’
* removing ‘/home/mikejames/anaconda3/lib/R/library/git2r’
Warning in install.packages :
  installation of package ‘git2r’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpQ8VN62/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

**Comment by ayorgo** [comment]
Try installing `git2r` from the terminal: `conda install r-git2r`

**Comment by stewid** [comment]
I have made a change to the configuration script. Does it work if you run the following from the command line?

```
git clone https://github.com/ropensci/git2r
cd git2r
make install
```

**Comment by ayorgo** [comment]
Thank you for the upgrade @stewid, but:
```
pinguin@pinguin:~/gva/programming/py/git2r$ make install
cd .. && R CMD INSTALL git2r
* installing to library ‘/home/pinguin/anaconda3/lib/R/library’
* installing *source* package ‘git2r’ ...
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /lib/cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... no
checking for sys/stat.h... no
checking for stdlib.h... no
checking for string.h... no
checking for memory.h... no
checking for strings.h... no
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... no
checking size of void*... 0
checking size of void*... 8
checking for library containing inflate... no
configure: error: in `/home/pinguin/gva/programming/py/git2r':
configure: error: 
  ---------------------------------------------
   The zlib library that is required to build
   git2r was not found.

   Please install:
     zlib1g-dev (package on e.g. Debian and Ubuntu)
     zlib-devel (package on e.g. Fedora, CentOS and RHEL)
   and try again.

   If the zlib library is installed on your
   system but the git2r configuration is
   unable to find it, you can specify the
   include and lib path to zlib with:
   R CMD INSTALL --configure-args='--with-zlib-include=INCLUDE_PATH --with-zlib-lib=LIB_PATH' git2r
  ---------------------------------------------
See `config.log' for more details
ERROR: configuration failed for package ‘git2r’
* removing ‘/home/pinguin/anaconda3/lib/R/library/git2r’
* restoring previous ‘/home/pinguin/anaconda3/lib/R/library/git2r’
Makefile:10: recipe for target 'install' failed
make: *** [install] Error 1
pinguin@pinguin:~/gva/programming/py/git2r$ sudo apt-get install zlib1g-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
0 to upgrade, 0 to newly install, 0 to remove and 51 not to upgrade.
```

So it seems to have made progress with detecting the size of `void*` but now it's missing `zlib` which appears to be installed.

**Comment by stewid** [comment]
@ayorgo I have updated the configure script. Could you please try again

**Comment by stewid** [comment]
@ayorgo could you please try again.

**Comment by ayorgo** [comment]
Nice and smooth run this time after `apt-get install libssh2-1-dev` :tada:

Thank you, @stewid!

**Comment by ayorgo** [comment]
Interestingly, I've run the old (0.19.0) version from a different instance of RStudio (installed from cran binaries https://www.rstudio.com/products/rstudio/download/ rather than via conda) and it worked just fine. So conda may be a culprit in this case.

**Comment by stewid** [comment]
@ayorgo Thanks for testing.
