### ISSUE TITLE
Supported R versions ... confirm support for R >= 3.0.2?

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#305]
DESCRIPTION says git2r works with R >= 3.0.2. There's some evidence from usethis that there may be trouble with R < 3.2 (https://travis-ci.org/r-lib/usethis/jobs/318456849). I haven't dug into it myself, FYI.

It would be good to include these older R versions in the Travis tests (e.g. via https://github.com/tidyverse/reprex/blob/master/.travis.yml). There's a nominal goal for packages in tidyverse and r-lib to support R >= 3.1 and we're gradually making that true / testing for that. And a few of those packages depend on git2r.

Thanks for taking a look when you can.

**Comment by stewid** [comment]
Thanks for the suggestion to add older R versions in the Travis tests. I have replaced some function calls, e.g. `trimws` and can confirm that it now works from R 3.1 (https://travis-ci.org/ropensci/git2r). Maybe it's simplest to bump git2r depends to R (>= 3.1)?

**Comment by jennybc** [comment]
> Maybe it's simplest to bump git2r depends to R (>= 3.1)

Sounds reasonable. It seems unlikely that someone has been counting on the nominal support for R < 3.1, because I think it was a claim but not actually true (right?).
