### ISSUE TITLE
repository() - error with empty line in /.git/config

### ISSUE THREAD

**Issue by brry** [ropensci/git2r#307]
If in an R package the `/.git/config` file contains an empty line at the end, `git2r::repository` returns the following error:
```
Error in validObject(.Object) : 
 invalid class "git_repository" object: Unable to open repository at 'path'
```

https://stackoverflow.com/q/47972548/1587132

**Comment by stewid** [comment]
I submitted a new version 0.21 to CRAN yesterday. Could you please check if it works with the new version, or if that also returns an error.

Thanks

**Comment by brry** [comment]
Yes, in the new version it works fine. Thanks so much!
