### ISSUE TITLE
Cant Install Git2r or devtools centos 6.8

### ISSUE THREAD

**Issue by Nabeelgujjar** [ropensci/git2r#308]
Selection: 1
also installing the dependency ‘git2r’

trying URL 'https://cloud.r-project.org/src/contrib/git2r_0.21.0.tar.gz'
Content type 'application/x-gzip' length 1155512 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://cloud.r-project.org/src/contrib/devtools_1.13.4.tar.gz'
Content type 'application/x-gzip' length 486348 bytes (474 KB)
==================================================
downloaded 474 KB

* installing *source* package ‘git2r’ ...
** package ‘git2r’ successfully unpacked and MD5 sums checked
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking how to run the C preprocessor... /lib/cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... no
checking for sys/stat.h... no
checking for stdlib.h... no
checking for string.h... no
checking for memory.h... no
checking for strings.h... no
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... no
checking size of void*... 0
checking size of void*... 8
checking for library containing inflate... no
checking for zlib... yes
checking for library containing EVP_EncryptInit... no
checking for openssl... yes
checking for library containing libssh2_version... no
checking for libssh2... yes
checking for gawk... gawk
checking for curl-config... /anaconda3/bin/curl-config
checking for the version of libcurl... 7.52.1
checking whether libcurl is usable... no
checking for struct stat.st_mtim... no
checking for struct stat.st_mtimespec... no
checking for struct stat.st_mtime_nsec... no
checking for futimens... no
checking for qsort_r... no
checking for qsort_s... no

  ----- Results of the git2r package configure -----

    OpenSSL to talk over HTTPS...........: yes
    LibSSH2 to enable the SSH transport..: yes

  --------------------------------------------------

configure: creating ./config.status
config.status: creating src/Makevars
** libs
/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -I/anaconda3/lib/R/include -DNDEBUG -I. -Ilibgit2/src -Ilibgit2/include -Ilibgit2/deps/http-parser       -D_FORTIFY_SOURCE=2 -O2 -I/anaconda3/include -DGIT_ARCH_64 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DGIT_OPENSSL -DLIBGIT2_NO_FEATURES_H -DGIT_SHA1_OPENSSL -DGIT_SSH -DGIT_USE_NSEC   -D_FORTIFY_SOURCE=2 -O2 -I/anaconda3/include   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/anaconda3/include  -c git2r.c -o git2r.o
make: /anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc: Command not found
make: *** [git2r.o] Error 127
ERROR: compilation failed for package ‘git2r’
* removing ‘/anaconda3/lib/R/library/git2r’
ERROR: dependency ‘git2r’ is not available for package ‘devtools’
* removing ‘/anaconda3/lib/R/library/devtools’

The downloaded source packages are in
        ‘/tmp/RtmpdU7m9x/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("devtools") :
  installation of package ‘git2r’ had non-zero exit status
2: In install.packages("devtools") :
  installation of package ‘devtools’ had non-zero exit status

**Comment by wcornwell** [comment]
I'm also having an issue installing git2r on Centos, which seems like it's the same as above or at least related.  For me this installed fine with R 3.3, so maybe it's something with R 3.4?

**Comment by wcornwell** [comment]
more info, in my case it's CentOS 6.3:

```{r}
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.3 (Final)

Matrix products: default
BLAS: /share/apps/R/3.4.2/lib64/R/lib/libRblas.so
LAPACK: /share/apps/R/3.4.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2  
```
and error message

```{r}
* installing *source* package ‘git2r’ ...
** package ‘git2r’ successfully unpacked and MD5 sums checked
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void*... 8
checking for library containing inflate... -lz
checking for library containing EVP_EncryptInit... -lcrypto
checking for library containing SSL_library_init... -lssl
checking for library containing OPENSSL_init_ssl... no
checking for library containing libssh2_version... -lssh2
checking for gawk... gawk
checking for curl-config... /usr/bin/curl-config
checking for the version of libcurl... 7.19.7
checking whether libcurl is usable... yes
checking for curl_free... yes
checking for struct stat.st_mtim... yes
checking for struct stat.st_mtimespec... no
checking for struct stat.st_mtime_nsec... no
checking for struct stat.st_mtim.tv_nsec... yes
checking for futimens... yes
checking for qsort_r... yes
checking for qsort_s... no

  ----- Results of the git2r package configure -----

    OpenSSL to talk over HTTPS...........: yes
    LibSSH2 to enable the SSH transport..: yes

  --------------------------------------------------

libgit2/src/transports/ssh.c: In function ‘ssh_agent_auth’:
libgit2/src/transports/ssh.c:293:2: error: unknown type name ‘LIBSSH2_AGENT’
  LIBSSH2_AGENT *agent = libssh2_agent_init(session);
  ^~~~~~~~~~~~~
libgit2/src/transports/ssh.c:293:25: warning: implicit declaration of function ‘libssh2_agent_init’ [-Wimplicit-function-declaration]
  LIBSSH2_AGENT *agent = libssh2_agent_init(session);
                         ^~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c:293:25: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
libgit2/src/transports/ssh.c:298:7: warning: implicit declaration of function ‘libssh2_agent_connect’ [-Wimplicit-function-declaration]
  rc = libssh2_agent_connect(agent);
       ^~~~~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c:303:7: warning: implicit declaration of function ‘libssh2_agent_list_identities’ [-Wimplicit-function-declaration]
  rc = libssh2_agent_list_identities(agent);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c:309:8: warning: implicit declaration of function ‘libssh2_agent_get_identity’ [-Wimplicit-function-declaration]
   rc = libssh2_agent_get_identity(agent, &curr, prev);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c:319:9: error: ‘LIBSSH2_ERROR_AUTHENTICATION_FAILED’ undeclared (first use in this function)
    rc = LIBSSH2_ERROR_AUTHENTICATION_FAILED;
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c:319:9: note: each undeclared identifier is reported only once for each function it appears in
libgit2/src/transports/ssh.c:323:8: warning: implicit declaration of function ‘libssh2_agent_userauth’ [-Wimplicit-function-declaration]
   rc = libssh2_agent_userauth(agent, c->username, curr);
        ^~~~~~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c:336:2: warning: implicit declaration of function ‘libssh2_agent_disconnect’ [-Wimplicit-function-declaration]
  libssh2_agent_disconnect(agent);
  ^~~~~~~~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c:337:2: warning: implicit declaration of function ‘libssh2_agent_free’ [-Wimplicit-function-declaration]
  libssh2_agent_free(agent);
  ^~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c: In function ‘_git_ssh_authenticate_session’:
libgit2/src/transports/ssh.c:371:9: warning: implicit declaration of function ‘libssh2_userauth_publickey’ [-Wimplicit-function-declaration]
    rc = libssh2_userauth_publickey(
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c:417:9: error: ‘LIBSSH2_ERROR_AUTHENTICATION_FAILED’ undeclared (first use in this function)
    rc = LIBSSH2_ERROR_AUTHENTICATION_FAILED;
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libgit2/src/transports/ssh.c: In function ‘shutdown_ssh’:
libgit2/src/transports/ssh.c:900:5: warning: implicit declaration of function ‘libssh2_exit’ [-Wimplicit-function-declaration]
     libssh2_exit();
     ^~~~~~~~~~~~
libgit2/src/transports/ssh.c: In function ‘git_transport_ssh_global_init’:
libgit2/src/transports/ssh.c:907:6: warning: implicit declaration of function ‘libssh2_init’ [-Wimplicit-function-declaration]
  if (libssh2_init(0) < 0) {
      ^~~~~~~~~~~~
make: *** [libgit2/src/transports/ssh.o] Error 1
ERROR: compilation failed for package ‘git2r’
```

**Comment by wcornwell** [comment]
Seems like it was about R finding the path to libssh2.  With some help from a linux guru, this worked for me:

```
mkdir $HOME/.R
echo "SHLIB_LIBADD=-Wl,-rpath,/share/apps/libssh2/1.8.0/lib" > $HOME/.R/Makevars
```

mileage may vary...

**Comment by stewid** [comment]
Thanks
