### ISSUE TITLE
Setting upstream and RStudio

### ISSUE THREAD

**Issue by thomascjohnson** [ropensci/git2r#309]
Hi! I believe this problem I'm having is related to this issue: https://github.com/ropensci/git2r/issues/133

I would like to be able to initiate a repository, push to it and set the upstream to the master and then be able to use git with RStudio, but it seems that RStudio's git functionality won't work until the user runs something like `git push -u origin master` 

It seems like in that previous issue the suggestion at closing is that `push` should do this, but it hasn't been the case for me. Is there a way to do this? Thanks!

**Comment by jennybc** [comment]
I think most/all of what you want is implemented in `usethis::use_github()`: https://github.com/r-lib/usethis/blob/master/R/github.R

Which you could either use or take the code as inspiration.

**Comment by thomascjohnson** [comment]
@jennybc you're a patron saint of R programmers

**Comment by stewid** [comment]
Thanks
