### ISSUE TITLE
[WIP] Change S4 methods to standard R functions

### ISSUE THREAD

**Issue by stewid** [ropensci/git2r#310]

**Comment by jennybc** [comment]
Very interesting title! What do you have planned? I basically have a whole package-worth of thoughts on related issues 🙂

https://github.com/jennybc/githug

Now, that is designed to talked to git and GitHub but still .... There's more in a private repo and also a design doc.

**Comment by stewid** [comment]
I want to simplify the design and with this change, most of the R functions are one-liners. I also want to replace the S4 classes with S3.

I think the functionality and user-interface of your githug package are really nice with very descriptive function names. I think we should merge these two projects 😃

**Comment by jennybc** [comment]
Cool! I'll know more about my priorities about a month from now, after my team has done more 2018 planning. But I can already state I am very interested in supporting this effort one way or another!
