### ISSUE TITLE
[WIP] Change S4 classes to S3

### ISSUE THREAD

**Issue by stewid** [ropensci/git2r#312]
- [x] cred_env
- [x] cred_ssh_key
- [x] cred_token
- [x] cred_user_pass
- [x] git_blame
- [x] git_blame_hunk
- [x] git_blob
- [x] git_branch
- [x] git_commit
- [x] git_diff
- [x] git_diff_file
- [x] git_diff_hunk
- [x] git_diff_line
- [x] git_fetch_head
- [x] git_merge_result
- [x] git_note
- [x] git_reference
- [x] git_reflog_entry
- [x] git_repository
- [x] git_signature
- [x] git_stash
- [x] git_tag
- [x] git_time
- [x] git_transfer_progress
- [x] git_tree

**Comment by jdblischak** [comment]
What's the timeline for releasing this new version to CRAN? The change from S4 to S3 is going to break  my projects that rely on git2r.

**Comment by stewid** [comment]
At the moment, I don't know. I'm waiting for the next release of libgit2 (version 0.27).

**Comment by jdblischak** [comment]
OK. For now I've pinned my package to depend on git2r <= 0.21.0. Please do let me know if you'd like me to test anything out as you make this upgrade. Thanks for all your hard work on this very useful package!
