### ISSUE TITLE
Windows and defaults for cred_ssh_key() 

### ISSUE THREAD

**Issue by ijlyttle** [ropensci/git2r#314]
Hi,

This follows a discussion that @jennybc and I were having over at jennybc/happy-git-with-r#74.

----

### Setup

As I understand, the defaults key locations for `cred_ssh_key()` are `publickey = "~/.ssh/id_rsa.pub"` ,  and `privatekey = "~/.ssh/id_rsa"`. 

On Windows, I run into an issue with the `"~"` directory,

```R
normalizePath("~")
```

```
#> [1] "C:\\Users\\username\\Documents"
```

because the location used by the RStudio IDE is `"C:/Users/username/.ssh/id_rsa"`. 

----

### Question 

Do you have a strong opinion on where to expect to find the `.ssh` directory on Windows, or more precisely, would you be open to changing the default expectation for Windows?

----

### Possible actions

To resolve this question in **usethis** for the location of git files @jennybc added this function [[ref](https://github.com/r-lib/usethis/blob/e253a790684ae2a6f6be30a6b009e301304ba74d/R/edit.R#L79-L85)]:

```R
git_user_dot_home <- function() {
  if (.Platform$OS.type == "windows") {
    Sys.getenv("USERPROFILE")
  } else {
    path.expand("~")
  }
}
```

where, on Windows:

```R
Sys.getenv("USERPROFILE")
```

```
#> [1] "C:/Users/username"
```

One alternative could be to change `cred_ssh_key()` accordingly.

However, I suspect that changing `cred_ssh_key()` might break some implementations. So as another alternative, how about `cred_ssh_key2()`? (Although I'm sure a better name could be found)

Thoughts?

**Comment by jennybc** [comment]
I will also point out that this logic is built into RStudio itself:

https://github.com/rstudio/rstudio/blob/32fca75c5a69ef3eb5b74d3b2907ca08d51ffcc3/src/cpp/session/modules/SessionVCS.cpp#L182-L196

So RStudio will place SSH keys here and look for them here. It appears to be the norm on Windows.

**Comment by stewid** [comment]
@ijlyttle Thanks for reporting this and please go ahead and create a pull request to improve the defaults.

**Comment by ijlyttle** [comment]
Will do!
