### ISSUE TITLE
Feature request: rev-list to list commits that affect a given file

### ISSUE THREAD

**Issue by jdblischak** [ropensci/git2r#324]
I would really like a quick and convenient way to obtain the commits that affect a given file. In Git, this can be done with the porcelain command `log` or the plumbing command `rev-list` ([git-rev-list](https://git-scm.com/docs/git-rev-list)). For example, to obtain the commits that affect the file `CONTRIBUTING.md` in this repo:

```
$ git rev-list --all -- CONTRIBUTING.md
f0fa093c5a67b5f1f48db3fea4ea48dd46c8a6c3
6f402d6709bf08971a61a4505582f70788124d6a
22f5fe7083c00202b7142ae46d0551e204d64552
8e956f0e4d58c1c4b6b8b7864734404467f0eb27
1a63d3f373df6f31f797f62bcaf8363ce8c70fc6
```

libgit2 has an implementation of rev-list in its examples directory: [rev-list.c](https://github.com/libgit2/libgit2/blob/master/examples/rev-list.c). Would it be possible to provide R bindings to this example?

Or is there an easier way to do this using the functions already available in git2r? My current R/git2r solution is to search through the entire Git history, checking each commit to see if the file was affected. This is slow, especially as the number of commits increases.

**Comment by stewid** [comment]
I'm using rev-walk in https://github.com/ropensci/git2r/blob/master/src/git2r_revwalk.c but if I remember correct it's not yet possible to filter by filename.
 
One way to achieve this now is to extract all blobs in the repository and then filter by filename. It's not super fast (takes ~7s on my machine) but I suspect it's faster than inspecting every commit.

```
blobs <- odb_blobs()
> blobs[blobs$name == "CONTRIBUTING.md", ]
                                          sha path            name  len                                   commit         author                when
2961 8c9931c11935556c57a20d6d12025807711fcec0      CONTRIBUTING.md 5598 8e956f0e4d58c1c4b6b8b7864734404467f0eb27    Karthik Ram 2014-08-07 13:23:19
2963 60e6aff0b946da7ce2b4409800997c1bc87c2339      CONTRIBUTING.md 5591 1a63d3f373df6f31f797f62bcaf8363ce8c70fc6 Stefan Widgren 2014-08-07 21:32:49
3054 09048354d36ae7ed434836679fd503d85fa2702a      CONTRIBUTING.md 7779 22f5fe7083c00202b7142ae46d0551e204d64552 Stefan Widgren 2014-08-12 12:19:58
3055 4405909db100386c54125525568a83bafe3c6bff      CONTRIBUTING.md 7791 6f402d6709bf08971a61a4505582f70788124d6a Stefan Widgren 2014-08-12 12:33:02
6314 c5cde7bc087d0595661f9ffc8737e5455f79e3b9      CONTRIBUTING.md 7811 f0fa093c5a67b5f1f48db3fea4ea48dd46c8a6c3        jennybc 2015-09-07 11:54:17
```

**Comment by jdblischak** [comment]
Thanks for the tip, @stewid. I should have asked for advice long ago. On my local machine, I get similar speeds to you. Unfortunately on my University HPC `odb_blobs()` is super slow (this is where my current approach is also particularly slow, which is I why I'm looking for speed improvements).

Throwing some ideas out there:
1. Would it be possible to cache the results of `odb_blobs()`? This way each time it is run, it only adds blobs that have been added to the Git repo since it was last executed.
1. Would this task of listing commits for a given file be able to be achieved quickly using your package [gix](https://github.com/stewid/gix)? Skimming the README, it looks like the package is useful for querying Git repositories.

Please let me know if there is anything I can do to help with this effort.

**Comment by jdblischak** [comment]
@stewid Turns out `odb_blobs()` was really slow on my HPC was because I had been using that repo for a long time (whereas the one cloned to my local machine was newer). Running [git gc](https://git-scm.com/docs/git-gc) reduced the number of objects from 3,249 to 1, which obviously made it run much faster.

**Comment by stewid** [comment]
Thanks, that is a very useful trick to speed things up.

I found a discussion in libgit2 about this feature https://github.com/libgit2/libgit2/issues/3041

**Comment by jdblischak** [comment]
> A combination of limiting the number of returned commits and filtering by path would allow a caller to ask for the last commit (in whatever sorting) to touch a particular path.

Yep! That's exactly what I'm looking for.

**Comment by jdblischak** [comment]
@stewid I'm a little confused by the correspondence between the SHAs recorded in the log and those recorded by the blobs. I wasn't surprised that some SHAs appear only in the log. As I expected, these were from merge commits (and also commits that only deleted files). However, there are also SHAs that are only returned by `odb_blobs()` but not `commits()`. As a concrete example, the git2r repo has 7 of these blobs. Interestingly, when I look these up in the Git repo, they have a commit message, but they are nowhere to be found on GitHub. I don't think they are [dangling blobs](https://stackoverflow.com/questions/18514659/git-what-is-a-dangling-commit-blob-and-where-do-they-come-from) because they have commit messages and aren't removed by garbage collection. Maybe they're be created by running `git commit --amend`? I'd appreciate any insight you could provide. See below for code to reproduce my observations.

```r
library("git2r")
packageVersion("git2r")
```

```
## [1] '0.21.0'
```

```r
tmp <- tempfile()
dir.create(tmp)
clone("git@github.com:ropensci/git2r.git", local_path = tmp)
```

```
## cloning into '/var/folders/5b/hbjnbkkd0t957rs24vxgvw200000gn/T//RtmpcDq7se/file48d6c21a84e'...
## Receiving objects:   1% (177/17659),   65 kb
## Receiving objects:  11% (1943/17659),  417 kb
## Receiving objects:  21% (3709/17659), 1985 kb
## Receiving objects:  31% (5475/17659), 2849 kb
## Receiving objects:  41% (7241/17659), 3393 kb
## Receiving objects:  51% (9007/17659), 4833 kb
## Receiving objects:  61% (10772/17659), 5569 kb
## Receiving objects:  71% (12538/17659), 6337 kb
## Receiving objects:  81% (14304/17659), 6881 kb
## Receiving objects:  91% (16070/17659), 7201 kb
## Receiving objects: 100% (17659/17659), 8769 kb, done.
```

```
## Local:    master /private/var/folders/5b/hbjnbkkd0t957rs24vxgvw200000gn/T/RtmpcDq7se/file48d6c21a84e/
## Remote:   master @ origin (git@github.com:ropensci/git2r.git)
## Head:     [d17df22] 2018-03-11: Fix possible protection stack imbalance
```

```r
r <- repository(path = tmp)
git_log <- commits(r)
git_log_sha <- vapply(git_log, function(x) x@sha, character(1))
blobs <- odb_blobs(r)
blobs_sha <- unique(blobs$commit)
length(git_log_sha)
```

```
## [1] 2267
```

```r
length(blobs_sha)
```

```
## [1] 2152
```

```r
length(intersect(git_log_sha, blobs_sha))
```

```
## [1] 2145
```

```r
length(union(git_log_sha, blobs_sha))
```

```
## [1] 2274
```

```r
# Commits in log but not the blobs - Deletions and merge commits
sha_log_only <- setdiff(git_log_sha, blobs_sha)
length(sha_log_only)
```

```
## [1] 122
```

```r
lookup(r, sha = sha_log_only[1])
```

```
## [bff5a21] 2018-03-10: Remove unused files
```

```r
lookup(r, sha = sha_log_only[2])
```

```
## [dec6ef9] 2018-02-25: Merge pull request #328 from ropensci/windows
```

```r
lookup(r, sha = sha_log_only[3])
```

```
## [358fcd2] 2018-02-23: Merge pull request #322 from jdblischak/windows-home
```

```r
# Commits in blobs but not in the log
sha_blobs_only <- setdiff(blobs_sha, git_log_sha)
length(sha_blobs_only)
```

```
## [1] 7
```

```r
for (i in 1:7) {
  print(lookup(r, sha = sha_blobs_only[i]))
}
```

```
## [41a0333] 2016-05-16: Add commits method with signature git_commit and git_branch
## [2bb1d1c] 2016-05-18: Add 'commits' method with signature 'git_tag'
## [e723826] 2018-02-24: Add an accessor function for the 'sha' slot
## [dbbc197] 2018-02-24: Add tests for sha function
## [c9bf6a9] 2018-02-25: Bump version to 0.21.9001
## [e7f28e3] 2018-02-25: Fix broken build
## [fcb96c5] 2018-02-25: Makevars.win: add definition 'STRICT_R_HEADERS' to 'PKG_CFLAGS'
```

**Comment by jdblischak** [comment]
Just a quick follow-up. I was able to confirm that I can create these blobs with `git commit --amend`. Not sure if that is the only way to create them though.

Would it be possible to add an argument to `odb_blobs()` to only return blobs that are connected to a commit? Right now I am filtering the blobs with the full Git history, but that will get slow as the number of commits increases.

**Comment by jdblischak** [comment]
Feature added in PR #372 :tada:
