### ISSUE TITLE
trying to get slot "sha" from an object (class "git_commit") that is not an S4 object 

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#326]
Just ran `devtools::release()` with dev devtools and dev git2r and got this message at the very end.

```
Error in substr(commit@sha, 1, 10) : 
  trying to get slot "sha" from an object (class "git_commit") that is not an S4 object 
```

Is this an issue for git2r or devtools? Perhaps devtools should be using an accessor vs. directly accessing a slot...

**Comment by stewid** [comment]
I think we need a `sha` accessor function in git2r so that the example above can be rewritten as `substr(sha(commit), 1, 10)`

**Comment by jennybc** [comment]
I'll close this since the S4 --> S3 transition is clearly already something that's getting some thought. It was a good example of how accessing slots via `@` is going to be an issue for revdeps.

**Comment by stewid** [comment]
I have created a branch `S4-classes` from the lastest release (tag v0.21.0). Moreover, I have added an accessor function `sha` in both `master` and `S4-classes`.
