### ISSUE TITLE
Problem with SSH on Windows

### ISSUE THREAD

**Issue by ijlyttle** [ropensci/git2r#327]
Hi,

A colleague and I noticed this behavior on Windows, using the CRAN version of git2r:

```
> push(repo, credentials = cred_ssh_key())
Error in .local(object, ...) : 
  Error in 'git2r_push': failed to start SSH session: Unable to exchange encryption keys
```

This used to work for me, but now it does not.

My colleague pointed out this recent notice from GitHub: 

https://github.com/blog/2507-weak-cryptographic-standards-removed

We also came across people having a similar problem in git-up/GitUp#241

The commonality between the two seems to be the use of libssh2. I'm afraid that this is as far as we have been able to dig.

It looks like you may be addressing this already in #325 - if this is the case, please accept my apologies and close this issue.

I can be of help to test solutions, but I don't think I have the skills to implement a solution.

Thanks!

**Comment by stewid** [comment]
@ijlyttle Thanks for reporting this.

@jeroen I think an updated version of libssh2 is needed to fix this, could you please update to 1.8 on https://github.com/rwinlib/libssh2

**Comment by jeroen** [comment]
OK. @ijlyttle can you try the dev version? Make sure `git2r` is __not loaded in R__ while you upgrade it:

```r
devtools::install_github("ropensci/git2r")
```

**Comment by ijlyttle** [comment]
I have tested the dev version on MacOS and Windows - Mac seems to be OK.

However, on Windows:

```
> library("git2r")
> repo <- repository(".")
> push(repo, credentials = cred_ssh_key())
Error in head.git_repository(object) : 
  Error in 'git2r_repository_head': Invalid repository
```

I don't even get to the point where I am asked for my ssh passphrase, so I suspect there is something else going on here.

**Comment by jeroen** [comment]
Was this issue caused by the upgrade of libgit2, or was it maybe not working before either?

**Comment by ijlyttle** [comment]
I suspect it was not working before.

**Comment by jeroen** [comment]
Could you open a new issue for this to make sure these problems do not get mixed up?

**Comment by stewid** [comment]
Thanks @jeroen 

I'm currently changing from S4 classes to S3 in the 'master' branch and I'm not ready to submit it to CRAN yet. I have therefore cherry-picked the fix to the `S4-classes` branch. @ijlyttle  could you please check that branch instead.

Unfortunatly, I get the following error on winbuilder
```
"D:/RCompile/recent/R/bin/i386/Rscript.exe" --vanilla "../tools/winlibs.R" 1.8.0
Error in download.file(sprintf("https://github.com/rwinlib/libssh2/archive/v%s.zip",  : 
  cannot open URL 'https://github.com/rwinlib/libssh2/archive/v1.8.0.zip'
In addition: Warning message:
In download.file(sprintf("https://github.com/rwinlib/libssh2/archive/v%s.zip",  :
  InternetOpenUrl failed: 'Die Serververbindung konnte nicht hergestellt werden.'
  Execution halted
```
which I think is also caused by the recent change on GitHub. @jeroen do you think that is the reason?

**Comment by jeroen** [comment]
Yes it's because of https://twitter.com/opencpu/status/966785019560775685

Hopefully winbuilder will be updated soon.

**Comment by ijlyttle** [comment]
@stewid, using the S4-classes branch (e7f28e3), I am still getting this on Windows 10:

```
> library("git2r")
> repo <- repository(".")
> push(repo, credentials = cred_ssh_key())
Error in .local(object, ...) : 
  Error in 'git2r_push': failed to start SSH session: Unable to exchange encryption keys
```

**Comment by jeroen** [comment]
FYI the win builder is fixed now.
