### ISSUE TITLE
Failed to start ssh session on Ubuntu LTS

### ISSUE THREAD

**Issue by djm158** [ropensci/git2r#330]
I am trying to install a package in a VSTS repository via `devtools` and getting this error:

`Installation failed: Error in 'git2r_clone': failed to start SSH session: Unable to exchange encryption keys`

I have installed `libssh2-1` and `libssh2-1-dev` from apt-get

```sh
sudo apt-get install libss2-1 libssh2-1-dev
```

and then re-installed `git2r` following [this stackoverflow post](https://stackoverflow.com/questions/33294383/devtoolsinstall-git-over-ssh)

```R
install.packages("git2r")
```

Output of `git2r::libgit2_features()`:
```
> libgit2_features()
$threads
[1] FALSE

$https
[1] FALSE

$ssh
[1] TRUE
```

Is there some way I can turn on verbose debugging to see more useful error information?

sessionInfo:
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] devtools_1.13.5 git2r_0.21.0

loaded via a namespace (and not attached):
[1] compiler_3.4.3 withr_2.1.1    memoise_1.1.0  digest_0.6.15
```

What I am running:

```R
pkdir <- "~/r-packages"
.libPaths(pkdir)
library(git2r)
library(devtools)
cred <- cred_ssh_key(publickey = "~/.ssh/id_rsa.pub", privatekey = "~/.ssh/id_rsa")
url <- "ssh://myrepo@vs-ssh.visualstudio.com:22/..."
install_git(url, branch="master", credentials = cred)
```

I have tested my VSTS ssh key by cloning this repository on the command line via `git` and that works.

**Comment by stewid** [comment]
Are you using the latest version 1.8 of libssh2?

**Comment by djm158** [comment]
Apparently Ubuntu Xenial's latest version is 1.5. I tied installing 1.8 from source but now when I try to reinstall git2r I'm getting the following error:

Error: package or namespace load failed for ‘git2r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/git2r/libs/git2r.so':
  libssh2.so.1: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/git2r’
* restoring previous ‘/usr/local/lib/R/site-library/git2r’

Is there a way to specify where to look for the libssh.so.1 file?

**Comment by stewid** [comment]
Thanks
