### ISSUE TITLE
Windows - This 'path' is not a git repository

### ISSUE THREAD

**Issue by surmann** [ropensci/git2r#334]
Hallo,

I get this error since some days with this code:

    library(git2r)
    repo = repository(".")
    # Fehler in repository(".") : The 'path' is not in a git repository

I use version `0.21.0.9002`

Best regards,
Dirk

**Comment by stewid** [comment]
Thanks for reporting this. I have made an update to the git2r code.
Could you please try again and see if it works.

**Comment by surmann** [comment]
I get the same error.

Is it possible to check the commit of the loaded package version?

**Comment by stewid** [comment]
Does the following return `NULL` or the path to the repository?
 
```
library(git2r)
discover_repository(".")
```

> Is it possible to check the commit of the loaded package version?

No, that is not possible.

**Comment by jennybc** [comment]
`devtools::session_info()` does reveal the SHA if you've installed from GitHub, I believe.

But not if you install from local clone.

**Comment by surmann** [comment]
@stewid This returns `NULL`. I used commit #198b4d6
@jennybc Thanks!

**Comment by stewid** [comment]
@surmann thanks. Does it return `NULL` if you give the full path to the repo e.g.

```
library(git2r)
discover_repository("c:/path/to/repo")
```

**Comment by surmann** [comment]
Ah! When I use `discover_repository(".")` inside a git repo, it returns the path plus `/.git/`.

**Comment by surmann** [comment]
@stewid `discover_repository("c:/path/to/repo")` from somewhere returns `"c:/path/to/repo/.git/"` as well as `discover_repository(".")` from the root directory of the git repo.

Does this help to solve this issue?

**Comment by surmann** [comment]
I try to install the current master version via `devtools`. Is it necessary to have a cygwin installation on my machine? It was not mandatory for the last git version of git2r, wasn't it?

**Comment by surmann** [comment]
This works:

    > str(git2r:::lookup_repository("."))
    List of 1
     $ path: chr "C:/path/to/repo/.git"
     - attr(*, "class")= chr "git_repository"

**Comment by surmann** [comment]
@stewid I tried version 91a169d4. Here is the result:

    > git2r::repository(".")
    Local:    master C:/Temp/git/test
    Head:     [5a98736] 2018-05-15: initial

On a repo without commits:

    > git2r::repository(".")
    Local:    C:/Temp/git/test
    Head:     nothing commited (yet)

Seems, that it is working now. Thanks!

**Comment by stewid** [comment]
Thanks
