### ISSUE TITLE
Feature request: specify branch to get commits from

### ISSUE THREAD

**Issue by nzbart** [ropensci/git2r#339]
Is it possible to add a parameter to the `commits` function to allow callers to specify the branch to get commits from? It appears to me that it is currently only possible to get commits from the currently checked out branch. It would be much faster and less disruptive if I could list commits from multiple branches without checking the branches out first.

**Comment by ocschwar** [comment]
I am glad to see I'm not the only one requesting this. What would it take ?

**Comment by stewid** [comment]
I'm working on it and I think I have a solution to this soon.

**Comment by ocschwar** [comment]
Awesome! I'm working on adding a traceability matrix to covr, and this feature would greatly enhance the value of wha tI'm doing.

**Comment by stewid** [comment]
I have added a `ref` parameter to the `commits` function to allow callers to specify the name of a tag or a branch to get the commits from, for example, `commits(repo, ref = "dev")` or `commits(repo, ref = "v0.23.0")`. The new functionality is in the master branch. Can you please check if this solves your use case?

**Comment by ocschwar** [comment]
Just tested it, and it works, and solved my use case beautifully! I'm about to post YA feature request over  in covr, that is only useful thanks to this new functionality. Many thanks!

**Comment by stewid** [comment]
@ocschwar Thanks for testing and glad to hear it works.
