### ISSUE TITLE
GitHub repo topics to review

### ISSUE THREAD

**Issue by maelle** [ropensci/git2r#346]
👋 @stewid 

I've added topics to the repo to increase its discoverability (through GitHub, and through rOpenSci registry which will use these topics)

![image](https://user-images.githubusercontent.com/8360597/40099315-cac19a0c-58df-11e8-9a5f-bcb02b9d3a30.png)

Feel free to change them until you're happy with the list! Thank you 😺

**Comment by stewid** [comment]
Great. Thanks @maelle

**Comment by maelle** [comment]
Thank _you_!
