### ISSUE TITLE
Handle installation on macOS when brew is missing

### ISSUE THREAD

**Issue by stewid** [ropensci/git2r#352]
Copy the autobrew solution by @jeroen, see for example, https://github.com/jeroen/openssl/blob/master/configure

**Comment by jeroen** [comment]
Want me to help with this?

**Comment by stewid** [comment]
Yes, that would be great.
Thanks

**Comment by stewid** [comment]
I have studied your anticonf scripts to do something similar in https://github.com/ropensci/git2r/blob/master/configure.ac I have also configured travis to test against a system without homebrew. Obviously it doesn't work yet since https://jeroen.github.io/autobrew/${PKG_BREW_NAME} doesn't exist. Am I on the right track?

I have been able to fix the configuration on travis with "brew_packages: libgit2". And it works on my fedora system with/without libgit2 (v026.3) installed.

Thanks

**Comment by jeroen** [comment]
Need to wait for this to get merged: https://github.com/Homebrew/homebrew-core/pull/29113

**Comment by jeroen** [comment]
OK this works now.

**Comment by stewid** [comment]
Thanks!
