### ISSUE TITLE
Support for git_stash_pop and git_stash_apply

### ISSUE THREAD

**Issue by jimhester** [ropensci/git2r#358]
This functionality was added fairly recently to libgit2 (https://github.com/libgit2/libgit2/pull/3018) however it doesn't seem like the R bindings expose this.

It would be pretty useful to have however, as right now while you can create a stash there is no way to pop it / apply it back.

**Comment by stewid** [comment]
I have added the `stash_pop` and `stash_apply` methods to the `stash-api` branch.

**Comment by jimhester** [comment]
Thanks!
