### ISSUE TITLE
ERROR: compilation failed for package 'Gs' (Generalised R-squared)on installation on Mac OS X 10.13.6 

### ISSUE THREAD

**Issue by hahajain** [ropensci/git2r#369]
I'm trying to install Gs with following command:

`install.packages("~/Downloads/Gs_1.0.tar", repos = NULL, type="source")
`

However, I'm getting the following error:

`Gs.cpp:6:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [Gs.o] Error 1
ERROR: compilation failed for package 'Gs'
* removing '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Gs'`

My sessioninfo is as follows:

`R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.12.18           arulesSequences_0.2-20 arules_1.6-1           Matrix_1.2-14         

loaded via a namespace (and not attached):
[1] compiler_3.5.1  tools_3.5.1     yaml_2.2.0      grid_3.5.1      lattice_0.20-35`

P.S. I've made sure that the r tools are installed as well as Command Line Tools.

**Comment by stewid** [comment]
This is not the repository for the 'Gs' package.
