### ISSUE TITLE
Problems install git2r

### ISSUE THREAD

**Issue by yjqiu** [ropensci/git2r#378]
When I tried to install git2r, I encountered the following error. I also tried to clone github and install locally but I ended up with the same error.

Error: package or namespace load failed for ‘git2r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/mnt/silencer2/home/serein/R/x86_64-redhat-linux-gnu-library/3.5/git2r/libs/git2r.so':
  /mnt/silencer2/home/serein/R/x86_64-redhat-linux-gnu-library/3.5/git2r/libs/git2r.so: undefined symbol: BIO_meth_set_read
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by stewid** [comment]
Hi,

BIO_meth_set_read is a function in OpenSSL. Have you installed the OpenSSL library? Another option is to install a system installation of libgit2 i.e. install the libgit2-dev package (Debian or Ubuntu) or libgit2-devel on e.g. Fedora, CentOS and RHEL.

**Comment by yjqiu** [comment]
We installed OpenSSL. The problem I suspect is that we have two OpenSSL version and somehow it used one in configuration and used another one for header files. But I am not sure how to correct it.

**Comment by ylyizhen** [comment]
I have the same error when trying to install "git2r" on Linux (RHEL). I also attempted the github solution as recommended and got the same error. We do have multiple versions of "openssl" installed. It becomes really confusing which one to choose. Any suggestion to fix this issue would be highly appreciated. 

=== error message below ===
Error: package or namespace load failed for ‘git2r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/lustre/workspace/home/yli/.conda/envs/R-3.5.1/lib/R/library/git2r/libs/git2r.so':
  /lustre/workspace/home/yli/.conda/envs/R-3.5.1/lib/R/library/git2r/libs/git2r.so: undefined symbol: sk_value
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/lustre/workspace/home/yli/.conda/envs/R-3.5.1/lib/R/library/git2r’
Warning in install.packages :
  installation of package ‘git2r’ had non-zero exit status

**Comment by stewid** [comment]
I would try to first install `libgit-devel` using e.g. `yum install libgit-devel` and then install git2r in R. `git2r` tries to first build against a system installation of libgit2, before building the bundled libgit2 in git2r.

**Comment by yjqiu** [comment]
It did resolve the problem after I installed libgit-devel. Thanks!

**Comment by stewid** [comment]
Glad to hear that it worked.
