### ISSUE TITLE
Add getPass option for cred_user_pass

### ISSUE THREAD

**Issue by jdblischak** [ropensci/git2r#379]
I like that I have the option to securely enter my SSH key passphrase via getPass (#252, #254). Would you be open to a PR that enables this option for `cred_user_pass()`? My proposed behavior would be to prompt with `getPass::getPass()` if 1) `username` is not `NULL`, 2) `password` is `NULL`, and 3) getPass is installed, e.g. the following would prompt me for my password:

```
push(credentials = cred_user_pass("jdblischak"))
```

Please let me know what you think of this proposed behavior. I am going to be mentoring some new open source contributors, and I thought this would be a nice feature for them to add.

**Comment by stewid** [comment]
I think it sounds great. Thanks

**Comment by cderv** [comment]
Recently there has been the `askpass` :package: that provides this kind of feature. 
https://github.com/jeroen/askpass/

Main advantage: no need for tcltk. 

Also there has been integration with git and ssh so that in R, git can use askpass to ask for credentials. 

Coming also soon : `credentials` :package:

https://github.com/r-lib/credentials

**Comment by jdblischak** [comment]
> Recently there has been the askpass package that provides this kind of feature.
https://github.com/jeroen/askpass/

@cderv Thanks for the suggestion! I'll  let @stewid decide if in the long-term he wants to make the switch from getPass to askpass across the entire package.

For the short-term I'd like to keep this Issue straightforward so that I can help mentor a new open source contributor. I've been happy with getPass so far (for both git2r and my package workflowr), and I've never received a bug report that it didn't work.

Also, just a sidenote, but it's crazy how popular askpass is. It was released a few months ago and is already one of the top CRAN downloads (I clearly didn't realize how popular its reverse dependency openssl is):

```
x <- cranlogs::cran_top_downloads(when = "last-month", count = 100)
x[x$package %in% c("askpass", "openssl"), ]
##    rank package  count       from         to
## 43   43 openssl 433027 2019-01-31 2019-03-01
## 64   64 askpass 365258 2019-01-31 2019-03-01
```

> Coming also soon : credentials package

That also looks useful. Thanks for the tip!

**Comment by stewid** [comment]
@cderv thanks for suggesting askpass and credentials.

For this change, I suggest that we keep using getPass. In the long-term (when they are both on CRAN) I think it's a good idea to change and use askpass and credentials instead.
