### ISSUE TITLE
FR: Type-stable version of lookup()

### ISSUE THREAD

**Issue by krlmlr** [ropensci/git2r#380]
Use case: I wanted to look up a commit for a tag, to compute ahead-behind information. (Perhaps it's another problem that `ahead_behind()` doesn't accept tags.)

- I use `lookup()`, hoping to find the commit that belongs to a known SHA
- I get a tag object
- `ahead_behind()` complains that it needs a commit

I see two ways out:

1. Commits, tags, branches etc. are synonymous, all functions that accept a commit also accept a tag or a branch
2. We gain `lookup_commit()` that guarantees to return a commit

See also https://principles.tidyverse.org/type-stability.html.

(Sorry for the lack of a reprex, I find one if needed.)

**Comment by stewid** [comment]
Thanks for reporting the problem and suggesting a solution. I have improved `ahead_behind()` and `descendent_of()` to also accept a tag or a branch. Could you please test that it solves your use case.

**Comment by stewid** [comment]
Please reopen the issue if the change didn't solve your use case

**Comment by krlmlr** [comment]
Thanks for the heads up, works for me now. Will try and report if I see any problems.

1f50723 manually checks the type of each input. Could we make use of a `lookup_commit()` S3 generic here, so that the dispatch happens automatically, and that other functions that could use this flexibility are easier to adapt?

**Comment by stewid** [comment]
I have now added the `lookup_commit` utility function to lookup a commit related to a git object and I'm also using that function in `ahead_behind` and `descendant_of` to simplify the code.
