### ISSUE TITLE
Cannot pull the repo, "Unable to authenticate with supplied credentials"   

### ISSUE THREAD

**Issue by JiaxiangBU** [ropensci/git2r#382]
```
> git2r::pull(".")
Error in fetch(repo = repo, name = branch_remote_name(upstream_branch),  : 
  Error in 'git2r_remote_fetch': Unable to authenticate with supplied credentials
```

I create a SSH key on the Github. However, I don't know how to input the argument `credentials`.
Anyone knows how to input it?

**Comment by cderv** [comment]
for github, you can use `GITHUB_PAT` environment using `git2r::cred_token()` as credentials.

`git2r::pull(".", credentials = git2r::cred_token())` should work. 

You can also setup SSH on your computer. This could help 
https://happygitwithr.com/ssh-keys.html

`git2r` uses ssh key by default when `credentials = NULL`. You must provide a credential object (`git2r::cred_*)` if you haven't set up SSH keys.

**Comment by JiaxiangBU** [comment]
Hi @cderv 

I try to make a reproducible example here but reprex is hard to do it.

``` r
git2r::pull(".", credentials = git2r::cred_token())
#> Error in lookup_repository(repo): The working directory is not in a git repository
```

<sup>Created on 2019-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

So I just paste the result in the console.

```
> git2r::cred_token()
$token
[1] "GITHUB_PAT"

attr(,"class")
[1] "cred_token"
> git2r::pull(credentials = git2r::cred_token())
Error in fetch(repo = repo, name = branch_remote_name(upstream_branch),  : 
  Error in 'git2r_remote_fetch': Unable to authenticate with supplied credentials
```

`git2r::cred_token()` works but `git2r::pull` gives the same result again.

**Comment by cderv** [comment]
To be sure, did you configure the environment variable `GITHUB_PAT` with your github token in it in `.Renviron` file ?

**Comment by JiaxiangBU** [comment]
Hi @cderv , thanks for your help, actually I don'y set the github pat. I follow the tutorial in https://happygitwithr.com/github-pat.html, and successfully run `git2r::pull(credentials = git2r::cred_token())` in the R session.
