### ISSUE TITLE
Enforced version of libgit2-dev newer than what's available in older versions of ubuntu

### ISSUE THREAD

**Issue by 1beb** [ropensci/git2r#385]
The newest available version of libgit2-dev is as follows for Ubuntu 16.04
```
$ sudo apt-get install libgit2-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libgit2-dev is already the newest version (0.25.1+really0.24.6-1)
```

However, you are enforcing 0.26 in configure.ac 

https://github.com/ropensci/git2r/commit/262c4c37a75fea1ceb9960a2da410c3aeba5186b

Looks like the decision was made based on Fedora. Not sure it applies to other operating systems other than Fedora.

**Comment by stewid** [comment]
To use a system installation of libgit2-dev it must be >=0.26 or the bundled libgit2 is used. The reason is simply that it's difficult to maintain git2r with older versions of libgit2 due to breaking API changes. I think the version of libgit-dev in Ubuntu 18.04 is >= 0.26.
