### ISSUE TITLE
Prioritize PKG_CONFIG path in configure

### ISSUE THREAD

**Issue by vobencha** [ropensci/git2r#398]
Hi,

It looks like the configure script does not prioritize libraries on the PKG_CONFIG path. This seems wrong but I may be missing something.

The system I'm working on has libssl installed in both a system location and in a module. I want to use libssl in the module which is on my PKG_CONFIG path. The module location is not added to CPPFLAGS or LIBS because the check on line 284 detects ssl and sets `have_ssl=yes` which then skips the search of the PKG_CONFIG path in line 289.

https://github.com/ropensci/git2r/blob/master/configure.ac#L284
https://github.com/ropensci/git2r/blob/master/configure.ac#L289

It seems the code blocks on lines 284 and 298 should be reversed. This would search PKG_CONFIG first and make the necessary additions to CPPFLAGS or LIBS. If ssl is not found then it could execute the more general check in line 284.

However, it looks like all searches in the configure script are handled this way. Was there a specific reason PKG_CONFIG path was deprioritized? Is the expectation that I should export all non-standard locations in CPPFLAGS?

Thanks.
Valerie

**Comment by stewid** [comment]
Thanks

**Comment by vobencha** [comment]
Thanks @stewid for the fix.
