### ISSUE TITLE
Check for min required version of libssh2

### ISSUE THREAD

**Issue by salim-b** [ropensci/git2r#420]
git2r installed from source on Ubuntu 16.04 Xenial (with the Debian package dependencies `libgit2`, `libgit2-dev`, `libssh2` and `libssh2-1-dev` present) just fails when attempting to clone a repo over SSH:

```
Error in 'git2r_clone': failed to start SSH session: Unable to exchange encryption keys
```

From [another issue](https://github.com/ropensci/git2r/issues/330#issuecomment-368767281) I conclude that git2r needs `libssh >= 1.8.0`, but Xenial ships `libssh 1.5.0`.

Therefore I think if would make sense for git2r to not only check if the libssh binary and its headers are present on the system but also check if the minimally required versions are met. That way, git2r would be built without SSH support on Xenial (instead of the user being left with broken SSH support in git2r).

**Comment by stewid** [comment]
Thanks
