### ISSUE TITLE
The check for git_oid_is_zero only reports warning, not error

### ISSUE THREAD

**Issue by fenguoerbian** [ropensci/git2r#432]
When I tried to install git2r 0.28 from source, the configuration check for libgit2 reports:

> checking whether the libgit2 version will work in git2r... yes
checking whether the libgit2 function git_buf_dispose is available... yes
checking whether the libgit2 constant GIT_OBJECT_ANY is available... yes
checking whether the libgit2 function git_error_last is available... yes
checking whether the libgit2 function git_oid_is_zero is available... yes
----- Results of the git2r package configure -----
  PKG_CFLAGS:  -DGIT2R_HAVE_BUF_DISPOSE -DGIT2R_HAVE_OBJECT_ANY -DGIT2R_HAVE_GIT_ERROR -DGIT2R_LIBGIT2_V0_99_0_RENAMES
  PKG_LIBS: -lgit2
--------------------------------------------------

This makes the installation procedure believes that I have libgit2>=0.99 installed but actually only libgit2 v0.28 is presented in my system. Therefore the installation fails without doubt.

I've checked the results from `configure` via `config.log`, it looks like the check for `git_oid_is_zero` only reports a warning, not an error:
> gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG     -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-8T8CYO/r-base-4.0.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c conftest.c -o conftest.o
conftest.c: In function 'main':
conftest.c:15:1: warning: implicit declaration of function 'git_oid_is_zero'; did you mean 'git_oid_iszero'? [-Wimplicit-function-declaration]
   15 | git_oid_is_zero(NULL);
      | ^~~~~~~~~~~~~~~
      | git_oid_iszero
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o conftest.so conftest.o -lgomp -L/usr/lib/R/lib -lR
configure:3398: result: yes

Then I manually break this part of check, make it report `no` always. Then the installation successes.

My question is: is there a flaw in the `configure` file when checking for recent version of libgit2?

**Comment by stewid** [comment]
Thanks for reporting this.

I'm not sure why the test only gives a warning and not an error. The `-Werror` option is passed to the configuration test to make all warnings become errors. However, it seems that the option `-Werror` is missing in your config.log. I think this can happen
if you have a `~/.R/Makevars` file that contains a setting for `PKG_CFLAGS`?

**Comment by fenguoerbian** [comment]
Thanks! I do have `PKG_CFLAGS=-fopenmp` in my `.Renviron`. After removing that the installation finishes without any problem.
