### ISSUE TITLE
Error when installing git2r from CRAN on Linux

### ISSUE THREAD

**Issue by MansMeg** [ropensci/git2r#448]
Hi!

I'm having problems when installing git2r from CRAN on a slurm cluster. I'm not sure what the problem is. I've read something about different lib2r versions, but I guess lib2git is shipped with the R package? Or should I install lib2git separately on linux? Sorry if this is a stupid question, but I could not really find an answer under installation in the README so hopefully this issue might help others as well.

```
In file included from libgit2/src/posix.h:155,
                 from libgit2/src/common.h:114,
                 from libgit2/src/runtime.h:10,
                 from libgit2/src/alloc.c:9:
libgit2/src/unix/posix.h:35:3: error: #error GIT_USE_NSEC defined but unknown struct stat nanosecond type
   35 | # error GIT_USE_NSEC defined but unknown struct stat nanosecond type
      |   ^~~~~
make: *** [libgit2/src/alloc.o] Error 1
ERROR: compilation failed for package ‘git2r’
* removing ‘/domus/h1/xmanma/R/x86_64-pc-linux-gnu-library/4.2/git2r’

The downloaded source packages are in
        ‘/scratch/RtmpkZyvFz/downloaded_packages’
Warning message:
In install.packages("git2r") :
  installation of package ‘git2r’ had non-zero exit status

> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /sw/apps/R/4.2.1/rackham/lib64/R/lib/libRblas.so
LAPACK: /sw/apps/R/4.2.1/rackham/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1 tools_4.2.1 
```

**Comment by stewid** [comment]
Hi,

I'm working on fixing that problem when building git2r using the bundled libgit2. But `git2r` can be built with a system installation of libgit2 instead of using the bundled source of libgit2. Therefore, it should work if you first install `libgit2` using:

- libgit2-dev   (package on e.g. Debian and Ubuntu)
- libgit2-devel (package on e.g. Fedora, CentOS and RHEL)
- libgit2       (Homebrew package on OS X)

Could you please try to install `git2r` after installing `libgit2`?

**Comment by stewid** [comment]
I've updated the configuration script and the version 1579b04156be13071b949ffaab188cc3fd597824 here on github should hopefully work for you.

**Comment by MansMeg** [comment]
Great! It fixed the problem! Thanks!
