### ISSUE TITLE
Building from source on Windows with RTools 4.0 and R 4.1.x

### ISSUE THREAD

**Issue by rps13** [ropensci/git2r#449]
I've been trying to build the latest version from source using RTools 4.0 targeting R version 4.1.x. I managed to get the compiler pointing to the correct directory (`lib-8.3.0`) for the crypto, ssl, ssh, and lz2 libraries that are downloaded by `tools/winlibs.R` by changing `Makevars.win`. However, I then get an error stating that the library file `libgit2.a` (also contained in the .zip downloaded by `tools/winlibs.R`) has undefined references to libiconv.
```
../windows/libgit2-1.4.2-fixed/lib-8.3.0/i386/libgit2.a(fs_path.c.obj):(.text+0x1f6b): undefined reference to `libiconv_open'
```

Is this is problem with the libraries packaged here: https://github.com/rwinlib/libgit2/ or am I missing additional libraries during compilation?

**Comment by rps13** [comment]
It turns out I need to add `-liconv` to `PKG_LIBS` in `src/Makevars.win` as well and then it compiles fine for both x86 and x64.

**Comment by stewid** [comment]
Thanks for reporting this. I've updated `src/Makevars.win` and added `-liconv` to `PKG_LIBS`.
