### ISSUE TITLE
cran update?

### ISSUE THREAD

**Issue by tdhock** [ropensci/git2r#470]
hi @stewid I got an email from CRAN today, which says that it plans to move git2r to the Archive, if there is no update before Oct 29. Do you plan to submit an update before then?

**Comment by stewid** [comment]
Hi @tdhock Yes, I'm working on an update before Oct 29.

**Comment by jeroen** [comment]
@stewid it seems the master branch is already fixed, you just need to submit it to CRAN...

**Comment by stewid** [comment]
A new version of git2r is now on CRAN.
