### ISSUE TITLE
Configuration specific for Solaris

### ISSUE THREAD

**Issue by stewid** [ropensci/git2r#48]
See https://github.com/libgit2/libgit2/blob/master/CMakeLists.txt

Fix configure.ac to check and handle specific configuration for Solaris

**Comment by stewid** [comment]
It fails to compile without openssl support, see http://cran.r-project.org/web/checks/check_results_git2r.html.

**Comment by stewid** [comment]
It works :smiley:  http://cran.r-project.org/web/checks/check_results_git2r.html

**Comment by gaborcsardi** [comment]
:+1:  Wow!

**Comment by karthik** [comment]
Amazing!
