### ISSUE TITLE
Skip ggplot2 dependency

### ISSUE THREAD

**Issue by gaborcsardi** [ropensci/git2r#75]
This is just something to think about. I think it might be worth separating plotting related functions to another package. ggplot2 has a lot of dependencies, which also makes installing `git2r` a "heavy" operation.

R packages tend to be heavy, and include a lot of loosely related functionality. I think this is a bad thing for maintenance, and it is better to have lighter packages.

**Comment by stewid** [comment]
Have implemented the plot method with base plot.

```r
repo <- repository("git2r")
plot(repo)
```
![image](https://cloud.githubusercontent.com/assets/1815965/6421923/9b7f8e10-bed3-11e4-93bc-97dd136b3724.png)
