### ISSUE TITLE
consider prefixing function names with git_*, so don't override base::* and shiny::* functions

### ISSUE THREAD

**Issue by bbest** [ropensci/git2r#80]
While the brevity of the existing git2r function names is convenient and relatable to the git command, at least the following functions get overridden:
- `base::merge`
- `base::diff`
- `shiny::tag`
- `shiny::tags`

While shiny may be less common, overriding the base library functions seems perilous. Of course there are easy ways around this, by prefixing functions with libraries or assigning as desired, but it would be less confusing if the names were more unique.

Might you consider prefixing git2r functions with `git_`, like `git_merge`? This still reads like the command line `git merge` and provides a globally unique function name without hazard of overriding other functions.

**Comment by jangorecki** [comment]
@bbest you can always use `importFrom` in your `NAMESPACE` file instead of `import`
